/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 96
#define YY_END_OF_BUFFER 97
static yyconst short int yy_acclist[365] =
    {   0,
       97,   95,   96,    5,   95,   96,    3,   96,   53,   95,
       96,    9,   95,   96,   64,   95,   96,   12,   95,   96,
       12,   95,   96,   11,   95,   96,    7,   95,   96,   11,
       95,   96,    7,   95,   96,   48,   95,   96,    7,   95,
       96,   23,   95,   96,   10,   95,   96,   24,   95,   96,
       47,   95,   96,   47,   95,   96,   47,   95,   96,   47,
       95,   96,   12,   95,   96,   95,   96,   11,   47,   95,
       96,   47,   95,   96,   47,   95,   96,   47,   95,   96,
       47,   95,   96,   47,   95,   96,   47,   95,   96,   47,
       95,   96,   47,   95,   96,   47,   95,   96,   47,   95,

       96,   47,   95,   96,   47,   95,   96,   47,   95,   96,
       47,   95,   96,   47,   95,   96,   47,   95,   96,   47,
       95,   96,   47,   95,   96,   63,   96,   56,   96,   54,
       96,   96,   74,   96,   67,   96,   65,   96,   96,   84,
       96,   78,   96,   96,   96,   96,   94,   96,   88,   96,
       96,   96,   50,   96,   52,   96,   51,   96,    2,    4,
        9,   48,   25,   27,   26,   47,   47,   47,   47,    6,
       47,   40,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   14,   47,   47,   30,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,

       47,   47,   47,   47,   47,   63,   55,   62,   60,   61,
       57,   59,   58,   74,   66,   73,   71,   72,   68,   70,
       69,   84,   77,   82,   83,   79,   81,   80,   94,   87,
       92,   93,   89,   91,   90,    4,   49,    1,   47,   47,
       47,    8,   47,   47,   47,   47,   47,   47,   13,   47,
       47,   47,   47,   47,   47,   29,   47,   47,   47,   47,
       47,   41,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   43,   47,   35,   47,   47,   47,   47,   76,
       86,   85,   75,   47,   47,   44,   47,   47,   38,   47,
       47,   47,   15,   47,   16,   47,   47,   47,   47,   47,

       47,   47,   47,   45,   47,   47,   47,   46,   47,   47,
       47,   47,   47,   47,   39,   47,   47,    8,    8,   47,
       17,   47,   34,   47,   47,   47,   47,   42,   47,   47,
       47,   33,   47,   47,   37,   47,   47,   32,   47,   31,
       47,   47,   28,   47,   21,   47,    9,   47,   36,   47,
       47,   19,   47,   47,   22,   47,    4,   47,   47,   18,
       47,   20,   47,    8
    } ;

static yyconst short int yy_accept[352] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,    4,    7,
        9,   12,   15,   18,   21,   24,   27,   30,   33,   36,
       39,   42,   45,   48,   51,   54,   57,   60,   63,   66,
       68,   72,   75,   78,   81,   84,   87,   90,   93,   96,
       99,  102,  105,  108,  111,  114,  117,  120,  123,  126,
      128,  130,  132,  133,  135,  137,  139,  140,  142,  144,
      145,  146,  147,  149,  151,  152,  153,  155,  157,  159,
      160,  160,  161,  161,  161,  162,  162,  162,  162,  163,
      163,  163,  164,  164,  165,  166,  167,  168,  169,  170,

      170,  170,  170,  170,  170,  171,  172,  174,  175,  176,
      177,  178,  179,  180,  181,  182,  183,  184,  185,  186,
      187,  189,  190,  192,  193,  194,  195,  196,  197,  198,
      199,  200,  201,  202,  203,  204,  205,  206,  207,  208,
      209,  210,  211,  212,  213,  214,  215,  216,  217,  218,
      219,  220,  221,  222,  223,  223,  224,  225,  226,  227,
      228,  229,  230,  230,  231,  232,  233,  234,  235,  236,
      236,  237,  237,  237,  237,  237,  237,  238,  239,  240,
      241,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      243,  243,  244,  245,  246,  247,  248,  249,  251,  252,

      253,  254,  255,  256,  258,  259,  260,  260,  261,  262,
      264,  265,  266,  267,  268,  269,  270,  271,  272,  273,
      275,  277,  278,  279,  280,  281,  282,  282,  282,  282,
      282,  282,  282,  283,  284,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  286,  288,  289,
      291,  292,  293,  295,  297,  298,  299,  300,  301,  302,
      303,  304,  306,  307,  308,  310,  311,  312,  313,  314,
      315,  317,  318,  318,  318,  318,  318,  318,  318,  318,
      319,  319,  320,  321,  323,  325,  326,  327,  328,  330,
      331,  332,  334,  335,  337,  338,  340,  342,  343,  345,

      347,  347,  347,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  349,  351,  352,  354,
      355,  357,  358,  358,  358,  358,  358,  358,  358,  359,
      360,  360,  360,  360,  360,  360,  360,  362,  364,  364,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    1,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       17,   16,   16,   16,   16,   16,   16,   18,   19,   20,
       21,   22,    1,    1,   23,   23,   23,   23,   23,   24,
       23,   23,   23,   23,   23,   23,   23,   25,   23,   23,
       23,   23,   23,   26,   23,   23,   23,   23,   23,   23,
       27,   28,   29,    1,   30,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   23,   40,   41,   42,   43,
       44,   45,   23,   46,   47,   48,   49,   23,   50,   51,
       52,   23,   53,    1,   54,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[55] =
    {   0,
        1,    1,    2,    1,    3,    1,    4,    1,    1,    1,
        1,    5,    6,    1,    1,    7,    8,    1,    1,    1,
        1,    1,    7,    7,    7,    7,    1,    9,    5,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,   10,   10
    } ;

static yyconst short int yy_base[375] =
    {   0,
        0,    0,   52,   53,   56,   57,   62,   63,   69,   72,
     1065, 1064, 1063, 1062, 1061, 1060, 1063, 1070, 1070,   97,
     1057,    0, 1054,   66, 1070, 1070,   71,   45, 1070,   78,
     1057, 1038,  103, 1037,    0, 1026, 1012, 1009,  104, 1051,
        0,   36,   52,   75, 1018,   77,   88, 1011,   94,  100,
     1020, 1006, 1003,  102,  107, 1000, 1001,   49, 1007,    0,
     1070, 1070,  140,    0, 1070, 1070,  146,    0, 1070, 1070,
     1038,  155,    0, 1070, 1039,  161, 1070, 1070, 1070,  110,
     1038,    0, 1035, 1036,    0, 1033, 1034, 1031,  130,  134,
      111, 1070,  150, 1070, 1070,    0,  996,  993,  965,  135,

      128,  143,  194,  150, 1070,  971,  929,  923,  922,  880,
      890,  877,  125,  126,  884,  869,  867,  864,  863,  858,
      896,  852,  167,  887,  848,  838,  824,  126,  771,  778,
      138,  768,  769,  762,  774,  764,  776,    0, 1070, 1070,
     1070, 1070, 1070, 1070, 1070,    0, 1070, 1070, 1070, 1070,
     1070, 1070, 1070,    0,  803, 1070, 1070, 1070, 1070, 1070,
     1070,    0,  804, 1070, 1070, 1070, 1070, 1070, 1070,  801,
        0,  798,  799,  795,  796,  793,  151,  198,  752,  762,
      704,  185,  209,  213,  168,  210,  177,  220,  203, 1070,
      214,  703,  696,  705,  700,  687,  685,  728,  695,  695,

      692,  694,  692,  718,  678,  682,  223,  667,  659,    0,
      673,  656,  670,  661,  654,  650,  643,  595,  582,    0,
      626,  588,  590,  586, 1070, 1070,  621,  618,  619,  618,
      613,  606, 1070, 1070,  576,  217,  226,  230,  229,  233,
      237,  244,  263,  243,  245,  265,  564,    0,  569,    0,
      561,  562,  596,  586,  544,  538,  527,  484,  466,  463,
      475,    0,  470,  463,  502,  455,  466,  462,  450,  459,
      428,  394,  420,  419,  416,  413,  413,  406,  294,  250,
      348,  246,  364,  407,  403,  250,  244,  250,    0,  249,
      241,    0,  257,    0,  254,    0,    0,  241,  279,  271,

      259,  256, 1070,    0,  257,  398,  399,  405,  434,    0,
      401,  402,  482,  488,  517,  211,  252,  198,  241,  168,
      191, 1070,  485,  569,  568,    0,  570,    0,  150,  129,
      486,  576,  587,  575,  590,  605,   89,   78,  634,  586,
        0,  684,  687,  690,  712,  741,  693,    0,  791, 1070,
      820,  830,  840,  850,  860,  870,  874,  880,  888,  898,
      908,  918,  925,  935,  945,  951,  959,  968,  977,  987,
      997, 1006, 1015, 1025
    } ;

static yyconst short int yy_def[375] =
    {   0,
      350,    1,  351,  351,  352,  352,  353,  353,  354,  354,
      355,  355,  355,  355,  355,  355,  350,  350,  350,  350,
      350,  356,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  357,  357,  357,  357,  358,  350,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  359,
      350,  350,  350,  360,  350,  350,  350,  361,  350,  350,
      350,  350,  362,  350,  350,  350,  350,  350,  350,  350,
      350,  363,  350,  350,  356,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  357,  357,  357,  357,  364,

      365,  350,  350,  366,  350,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  359,  350,  350,
      350,  350,  350,  350,  350,  360,  350,  350,  350,  350,
      350,  350,  350,  361,  350,  350,  350,  350,  350,  350,
      350,  362,  350,  350,  350,  350,  350,  350,  350,  350,
      363,  350,  367,  368,  350,  350,  350,  350,  357,  357,
      357,  364,  350,  369,  365,  350,  370,  358,  350,  350,
      366,  357,  357,  357,  357,  357,  357,  357,  357,  357,

      357,  357,  357,  357,  357,  357,  350,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  350,  350,  371,  372,  367,  350,
      368,  350,  350,  350,  357,  350,  364,  364,  369,  365,
      365,  370,  358,  364,  365,  350,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  371,  350,  372,  350,  350,  350,  350,  364,
      350,  365,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,

      350,  350,  350,  279,  364,  373,  364,  364,  350,  281,
      373,  365,  365,  365,  350,  357,  357,  357,  357,  357,
      357,  350,  373,  374,  364,  309,  365,  315,  357,  357,
      373,  373,  373,  374,  364,  365,  357,  357,  350,  373,
      339,  373,  373,  373,  373,  350,  373,  346,  373,    0,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350
    } ;

static yyconst short int yy_nxt[1125] =
    {   0,
       18,   19,   20,   19,   21,   22,   23,   24,   25,   26,
       26,   27,   28,   29,   26,   30,   30,   31,   29,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   25,   41,
       42,   43,   44,   45,   46,   47,   48,   35,   49,   35,
       50,   51,   52,   53,   54,   55,   56,   57,   35,   58,
       35,   59,   24,   25,   61,   61,   62,   62,   65,   65,
       89,   89,   66,   66,   69,   69,   70,   70,   71,   71,
       87,   74,   88,   75,   74,   87,   75,   88,  106,   63,
       63,  207,  107,   67,   67,   70,  135,  136,   70,   72,
       72,   90,  207,   89,   89,  108,   76,  109,   80,   76,

       80,   81,   82,   83,   93,  110,   93,   87,  100,   88,
      101,   80,  178,   80,  178,  111,  102,  114,  112,  103,
      103,   70,   70,   94,   70,   70,  116,  115,  117,  121,
      125,  118,  129,  119,  186,  122,  123,  131,  126,  183,
      124,  132,  139,   90,  140,   89,   89,  130,  147,  177,
      177,   93,  148,   93,   87,  187,   88,  156,  103,  103,
      198,  188,  184,  164,  199,  124,  177,  177,  214,  338,
      207,  141,  200,  124,  236,  142,  217,  149,  190,  185,
      218,  150,  143,  241,  337,  144,  157,  145,  151,  236,
      158,  152,  165,  153,  207,  187,  166,  159,  330,  178,

      160,  178,  161,  167,  242,  188,  168,  189,  169,  103,
      103,  209,  184,  233,  210,  182,  234,  238,  246,  246,
      188,  188,  190,  243,  244,  188,  245,   87,  188,   88,
      236,  182,  102,  238,  236,  103,  103,  190,  190,  236,
      239,  279,  190,  236,  207,  190,  185,  236,  281,  124,
      241,  236,  236,  184,  236,  207,  239,  184,  280,  329,
      187,  236,  322,  322,  187,  282,  243,  244,  279,  245,
      184,  242,  187,  187,  207,  102,  188,  184,  103,  103,
      246,  246,  207,  321,  184,  280,  320,  124,  124,  319,
      318,  317,  316,  190,  182,  182,  182,  304,  305,  182,

      306,  182,  182,  182,  182,  182,  307,  182,  182,  308,
      308,  182,  182,  182,  182,  182,  309,  309,  309,  309,
      182,  184,  182,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  182,  182,  185,  185,
      185,  310,  311,  185,  312,  185,  185,  185,  185,  185,
      313,  185,  185,  314,  314,  185,  185,  185,  185,  185,
      315,  315,  315,  315,  185,  187,  185,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,

      185,  185,  241,  236,  238,  241,  207,  238,  236,  236,
      207,  124,  303,  281,  308,  308,  279,  303,  325,  302,
      308,  308,  276,  301,  274,  324,  184,  300,  324,  187,
      282,  207,  184,  280,  182,  182,  182,  182,  236,  182,
      182,  182,  182,  182,  182,  279,  182,  182,  182,  326,
      326,  182,  182,  182,  182,  182,  326,  326,  326,  326,
      182,  184,  280,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  182,  182,  236,  241,
      241,  238,  238,  299,  236,  298,  297,  314,  314,  281,

      124,  327,  296,  314,  314,  207,  295,  294,  293,  187,
      292,  291,  324,  324,  290,  187,  282,  185,  185,  185,
      185,  185,  185,  236,  185,  185,  185,  185,  281,  185,
      185,  185,  328,  328,  185,  185,  185,  185,  185,  328,
      328,  328,  328,  185,  187,  282,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  185,
      185,  323,  236,  332,  289,  333,  236,  323,  288,  332,
      241,  333,  238,  335,  335,  336,  336,  339,  287,  207,
      241,  241,  238,  238,  236,  184,  334,  187,  339,  207,

      286,  279,  334,  324,  340,  335,  335,  285,  284,  283,
      124,  236,  278,  324,  324,  340,  281,  184,  280,  232,
      336,  336,  277,  230,  276,  274,  272,  271,  270,  207,
      269,  268,  187,  282,  323,  323,  323,  341,  342,  323,
      343,  323,  323,  323,  323,  323,  344,  323,  323,  345,
      345,  323,  323,  323,  323,  323,  346,  346,  346,  346,
      323,  324,  323,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  323,  323,  241,  267,
      238,  241,  266,  238,  241,  339,  238,  241,  339,  238,

      265,  264,  263,  262,  261,  345,  345,  260,  349,  349,
      259,  324,  340,  258,  324,  340,  241,  324,  238,  124,
      324,  207,  257,  339,  256,  347,  255,  345,  345,  254,
      253,  207,  252,  251,  250,  249,  248,  247,  124,  324,
      340,  323,  323,  323,  323,  241,  323,  238,  323,  323,
      323,  323,  339,  323,  323,  323,  348,  348,  323,  323,
      323,  323,  323,  348,  348,  348,  348,  323,  324,  340,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  323,  323,  241,  124,  238,  235,  234,

      233,  232,  339,  230,  228,  227,  349,  349,  226,  225,
      224,  223,  222,  221,  220,  219,  216,  215,  324,  340,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       85,  213,   85,   85,   85,   85,   85,   85,   85,   85,
       96,   96,  104,  104,  212,  104,  104,  104,  138,  211,
      207,  138,  138,  138,  138,  138,  208,  138,  146,  207,

      146,  206,  146,  146,  146,  146,  205,  146,  154,  204,
      203,  202,  154,  154,  154,  154,  201,  154,  162,  197,
      196,  162,  162,  162,  162,  171,  195,  171,  171,  171,
      171,  171,  171,  171,  171,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  191,  194,  191,  191,  229,
      229,  229,  229,  229,  229,  229,  193,  229,  231,  231,
      231,  231,  231,  231,  231,  192,  231,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  273,  273,  273,

      273,  273,  273,  273,  124,  273,  275,  275,  275,  275,
      275,  275,  275,  181,  275,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  180,  179,  176,  175,  174,
      173,  172,  170,  163,  155,  137,  134,  133,  124,  128,
      127,  120,  113,  105,   99,   98,   97,   95,   92,   91,
       86,   84,  350,   79,   79,   78,   78,   77,   77,   17,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,

      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350
    } ;

static yyconst short int yy_chk[1125] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    3,    4,    5,    6,
       28,   28,    5,    6,    7,    8,    7,    8,    7,    8,
       24,    9,   24,    9,   10,   27,   10,   27,   42,    3,
        4,  338,   42,    5,    6,    9,   58,   58,   10,    7,
        8,   30,  337,   30,   30,   43,    9,   43,   20,   10,

       20,   20,   20,   20,   33,   44,   33,   33,   39,   33,
       39,   80,   91,   80,   91,   44,   39,   46,   44,   39,
       39,    9,    9,   33,   10,   10,   47,   46,   47,   49,
       50,   47,   54,   47,  101,   49,   49,   55,   50,  100,
       49,   55,   63,   89,   63,   89,   89,   54,   67,   90,
       90,   93,   67,   93,   93,  101,   93,   72,  102,  102,
      113,  104,  100,   76,  114,  113,  177,  177,  128,  330,
      123,   63,  114,  128,  185,   63,  131,   67,  104,  187,
      131,   67,   63,  187,  329,   63,   72,   63,   67,  182,
       72,   67,   76,   67,  321,  185,   76,   72,  320,  178,

       72,  178,   72,   76,  187,  103,   76,  103,   76,  103,
      103,  123,  182,  183,  123,  184,  186,  184,  189,  189,
      183,  186,  103,  188,  188,  191,  188,  207,  236,  207,
      237,  239,  188,  239,  238,  188,  188,  183,  186,  240,
      184,  238,  191,  241,  319,  236,  242,  244,  241,  318,
      242,  245,  282,  237,  280,  317,  239,  238,  238,  316,
      240,  305,  302,  301,  241,  241,  243,  243,  305,  243,
      244,  242,  245,  282,  300,  243,  246,  280,  243,  243,
      246,  246,  299,  298,  305,  305,  295,  293,  291,  290,
      288,  287,  286,  246,  279,  279,  279,  279,  279,  279,

      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,

      281,  281,  306,  307,  306,  311,  285,  311,  312,  308,
      284,  283,  278,  312,  307,  307,  308,  277,  308,  276,
      308,  308,  275,  274,  273,  306,  307,  272,  311,  312,
      312,  271,  308,  308,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  313,  323,
      331,  323,  331,  270,  314,  269,  268,  313,  313,  314,

      267,  314,  266,  314,  314,  265,  264,  263,  261,  313,
      260,  259,  323,  331,  258,  314,  314,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  324,  325,  324,  257,  324,  327,  334,  256,  334,
      332,  334,  332,  325,  325,  327,  327,  332,  255,  254,
      340,  333,  340,  333,  335,  325,  324,  327,  333,  253,

      252,  335,  334,  332,  332,  335,  335,  251,  249,  247,
      235,  336,  232,  340,  333,  333,  336,  335,  335,  231,
      336,  336,  230,  229,  228,  227,  224,  223,  222,  221,
      219,  218,  336,  336,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  342,  217,
      342,  343,  216,  343,  344,  342,  344,  347,  343,  347,

      215,  214,  213,  212,  211,  344,  344,  209,  347,  347,
      208,  342,  342,  206,  343,  343,  345,  344,  345,  205,
      347,  204,  203,  345,  202,  345,  201,  345,  345,  200,
      199,  198,  197,  196,  195,  194,  193,  192,  181,  345,
      345,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  349,  180,  349,  179,  176,

      175,  174,  349,  173,  172,  170,  349,  349,  163,  155,
      137,  136,  135,  134,  133,  132,  130,  129,  349,  349,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      356,  127,  356,  356,  356,  356,  356,  356,  356,  356,
      357,  357,  358,  358,  126,  358,  358,  358,  359,  125,
      124,  359,  359,  359,  359,  359,  122,  359,  360,  121,

      360,  120,  360,  360,  360,  360,  119,  360,  361,  118,
      117,  116,  361,  361,  361,  361,  115,  361,  362,  112,
      111,  362,  362,  362,  362,  363,  110,  363,  363,  363,
      363,  363,  363,  363,  363,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  366,  109,  366,  366,  367,
      367,  367,  367,  367,  367,  367,  108,  367,  368,  368,
      368,  368,  368,  368,  368,  107,  368,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  371,  371,  371,

      371,  371,  371,  371,  106,  371,  372,  372,  372,  372,
      372,  372,  372,   99,  372,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,   98,   97,   88,   87,   86,
       84,   83,   81,   75,   71,   59,   57,   56,   53,   52,
       51,   48,   45,   40,   38,   37,   36,   34,   32,   31,
       23,   21,   17,   16,   15,   14,   13,   12,   11,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,

      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#define INITIAL 0
#line 2 "scanner.l"
    #include <stdio.h>
    #include <ctype.h>
    #include <stdlib.h>
    #include <string.h>
    #include "parser.tab.h"

    #pragma warning (disable: 4005)
    #include "parser.hpp"
    #include "astNodes.hpp"
    using namespace std;

    #define Stack_SIZE 100
    void push();
    void pop();
    void show();

    int top = -1;
    int stack_arr[Stack_SIZE];

    void push(int insert_item)
    {
        if (top == Stack_SIZE - 1)
            printf("\nOverflow!!");

        else
        {
            top++;
            stack_arr[top] = insert_item;
        }
    }

    void pop()
    {
        if (top == -1)
            printf("\nUnderflow!!");

        else
            top--;
    }

    void stackshow()
    {
        if (top == -1)
            printf("\nUnderflow!!");

        else
        {
            printf("\nElements present in the stack: \n");
            for (int i = top; i >= 0; --i)
                printf("%d\n", stack_arr[i]);
        }
    } 

    #define keyword_size 10
    char keyword[keyword_size];

    #define MAX_STR_CONST 256
    char string_buf[MAX_STR_CONST];
    char *string_buf_ptr;

    int current_indentation = 0;
    int spaces = 0;

    extern YYSTYPE yylval; 
#define DOUBLE_STRING 1

#define SINGLE_STRING 2

#define COMMENT_STRING 3

#define COMMENT_STRING_DOUBLE 4

#define INDENTSTATE 5

#define DEDENTALLSTATE 6

#define DEDENTSTATE 7

#line 865 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 115 "scanner.l"


#line 1019 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 351 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1070 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 117 "scanner.l"
{
                            BEGIN(INDENTSTATE);
                            if(top < 0)
                                push(0);

                            spaces = 0;
                            for(int i = 0; i < yyleng; i++){
                                if (yytext[i] == ' ') {
                                    spaces++;
                                } else if (yytext[i] == '\t') {
                                    spaces += 8;
                                }
                            }
                            push(spaces);

                            current_indentation = spaces;
                            unput(' ');

                            return NEWLINE;
                        }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 138 "scanner.l"
{
                            if(top < 0)
                                push(0);

                            spaces = 0;
                            for(int i = 0; i < yyleng; i++){
                                if (yytext[i] == ' ') {
                                    spaces++;
                                } else if (yytext[i] == '\t') {
                                    spaces += 8;
                                }
                            }
                            current_indentation = spaces;

                            unput(' ');
                            BEGIN(DEDENTSTATE);
                            return NEWLINE;
                        }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 157 "scanner.l"
{ 
                            BEGIN(DEDENTALLSTATE);
                            unput(' ');
                            return NEWLINE;
                        }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 163 "scanner.l"
{}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(DOUBLE_STRING):
case YY_STATE_EOF(SINGLE_STRING):
case YY_STATE_EOF(COMMENT_STRING):
case YY_STATE_EOF(COMMENT_STRING_DOUBLE):
case YY_STATE_EOF(INDENTSTATE):
case YY_STATE_EOF(DEDENTALLSTATE):
case YY_STATE_EOF(DEDENTSTATE):
#line 165 "scanner.l"
{
                    BEGIN(DEDENTALLSTATE);
                    unput(' ');

                    if(stack_arr[top] == 0)
                        return 0;
                }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 173 "scanner.l"
{}
	YY_BREAK
case 6:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 175 "scanner.l"
{}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 177 "scanner.l"
{yylval.strval = strdup(yytext); return yytext[0];}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 179 "scanner.l"
{return ARRAY;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 181 "scanner.l"
{}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 183 "scanner.l"
{yylval.strval = strdup(yytext); return yytext[0];}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 185 "scanner.l"
{yylval.strval = strdup(yytext); return yytext[0];}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 187 "scanner.l"
{yylval.strval = strdup(yytext); return yytext[0];} 
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 189 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return DEF;
                        }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 194 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return IF;
                        }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 199 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return ELIF;
                        }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 204 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return ELSE;
                        }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 209 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return BREAK;
                        }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 214 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return CONTINUE;
                        }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 219 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return GLOBAL;
                        }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 224 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return NONLOCAL;
                        }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 229 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return YIELD;
                        }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 234 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return RETURN;
                        }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 239 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return LT;
                        }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 244 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return GT;
                        }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 249 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return LTE;
                        }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 254 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return GTE;
                        }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 259 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return EQUAL;
                        }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 264 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return WHILE;
                        }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 269 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return FOR;
                        }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 274 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return IN;
                        }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 279 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return RANGE;
                        }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 284 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return PRINT;
                        }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 289 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return INPUT;
                        }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 294 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return CLASS;
                        }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 299 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return TRY;
                        }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 304 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return EXCEPT;
                        }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 309 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return MATCH;
                        }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 314 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return CASE;
                        }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 319 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return WITH;
                        }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 324 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return AS;
                        }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 329 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return INT;
                        }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 334 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return FLOAT;
                        }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 339 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return STR;
                        }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 344 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return BOOL;
                        }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 349 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return LIST;
                        }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 354 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return PASS;
                        }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 360 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return ID;
                        }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 365 "scanner.l"
{
                            yylval.intval = atoi(yytext);
                            return INT_NUMBER;
                        }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 370 "scanner.l"
{
                            yylval.flval = atof(yytext);
                            return FLOAT_NUMBER;
                        }
	YY_BREAK

case 50:
YY_RULE_SETUP
#line 377 "scanner.l"
{
        BEGIN(INITIAL);
        return INDENT;
    }
	YY_BREAK


case 51:
YY_RULE_SETUP
#line 384 "scanner.l"
{

        int flag = 1;
        for (int i = 0; i <= top; i++) {
            if (current_indentation == stack_arr[i])
                flag = 0;
        }

        if(flag)
            return INDENTERROR;

        int end = 1;
        while(current_indentation < stack_arr[top])
        {
            unput(' ');
            BEGIN(DEDENTSTATE);
            end = 0;
            pop();

            return DEDENT;
        }

        if(end)
            BEGIN(INITIAL);

    }
	YY_BREAK


case 52:
YY_RULE_SETUP
#line 413 "scanner.l"
{
        if (top < 0)
            push(0);

        if (stack_arr[top] > 0) {
            while (top > 0) {
                unput(' ');
                BEGIN(DEDENTALLSTATE);
                pop();

                return DEDENT;
            }
        } else {
            BEGIN(INITIAL);
        }
    }
	YY_BREAK

case 53:
YY_RULE_SETUP
#line 431 "scanner.l"
{ string_buf_ptr = string_buf; BEGIN(DOUBLE_STRING); }    
	YY_BREAK

case 54:
YY_RULE_SETUP
#line 434 "scanner.l"
{*string_buf_ptr = '\0'; BEGIN(INITIAL); return STRING;} 
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 435 "scanner.l"
{              }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 436 "scanner.l"
{printf("error in line %d\n", yylineno); BEGIN(INITIAL);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 437 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 438 "scanner.l"
{*string_buf_ptr++ = '\t';}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 439 "scanner.l"
{*string_buf_ptr++ = '\r';}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 440 "scanner.l"
{*string_buf_ptr++ = '\b';}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 441 "scanner.l"
{*string_buf_ptr++ = '\f';}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 442 "scanner.l"
{*string_buf_ptr++ = '\"';} 
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 443 "scanner.l"
{
        char *yptr = yytext;
        while ( *yptr )
            *string_buf_ptr++ = *yptr++;        
    }
	YY_BREAK

case 64:
YY_RULE_SETUP
#line 450 "scanner.l"
{ string_buf_ptr = string_buf; BEGIN(SINGLE_STRING); }    
	YY_BREAK

case 65:
YY_RULE_SETUP
#line 452 "scanner.l"
{*string_buf_ptr = '\0'; BEGIN(INITIAL); return STRING;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 453 "scanner.l"
{              }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 454 "scanner.l"
{printf("line%d, ERROR: new line in string\n", yylineno); BEGIN(INITIAL);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 455 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 456 "scanner.l"
{*string_buf_ptr++ = '\t';}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 457 "scanner.l"
{*string_buf_ptr++ = '\r';}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 458 "scanner.l"
{*string_buf_ptr++ = '\b';}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 459 "scanner.l"
{*string_buf_ptr++ = '\f';}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 460 "scanner.l"
{*string_buf_ptr++ = '\'';} 
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 461 "scanner.l"
{
        char *yptr = yytext;
        while ( *yptr )
            *string_buf_ptr++ = *yptr++;        
    }
	YY_BREAK

case 75:
YY_RULE_SETUP
#line 468 "scanner.l"
{   
                            int i = 0;
                            strcpy(keyword, " ");

                            while(yytext[i] != ' ') {
                                if (yytext[i] == '\'') 
                                    break;

                                keyword[i] = yytext[i];
                                i++;
                            }

                            string_buf_ptr = string_buf; BEGIN(COMMENT_STRING); 

                            if (strcmp(keyword, "=") == 0) {
                                return yytext[0];
                            }
                            else if (strcmp(keyword, "(") == 0 || strcmp(keyword, "{") == 0 || strcmp(keyword, "[") == 0) {
                                return yytext[0];
                            }

                            else {
                                if ( strcmp(keyword, "return") == 0) {
                                    return RETURN;
                                }
                            }

                            
                        }
	YY_BREAK

case 76:
YY_RULE_SETUP
#line 499 "scanner.l"
{*string_buf_ptr = '\0'; BEGIN(INITIAL); return STRING;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 500 "scanner.l"
{}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 501 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 502 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 503 "scanner.l"
{*string_buf_ptr++ = '\t';}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 504 "scanner.l"
{*string_buf_ptr++ = '\r';}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 505 "scanner.l"
{*string_buf_ptr++ = '\b';}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 506 "scanner.l"
{*string_buf_ptr++ = '\f';}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 507 "scanner.l"
{
        char *yptr = yytext;
        while ( *yptr )
            *string_buf_ptr++ = *yptr++;        
    }
	YY_BREAK

case 85:
YY_RULE_SETUP
#line 514 "scanner.l"
{   
                            int i = 0;
                            strcpy(keyword, " ");

                            while(yytext[i] != ' ') {
                                if (yytext[i] == '\"') 
                                    break;

                                keyword[i] = yytext[i];
                                i++;
                            }

                            string_buf_ptr = string_buf; BEGIN(COMMENT_STRING_DOUBLE); 

                            if (strcmp(keyword, "=") == 0) {
                                return yytext[0];
                            }

                            else if (strcmp(keyword, "(") == 0 || strcmp(keyword, "{") == 0 || strcmp(keyword, "[") == 0) {
                                return yytext[0];
                            }

                            else {
                                if ( strcmp(keyword, "return") == 0) {
                                    return RETURN;
                                }
                            }
                            
                        }
	YY_BREAK

case 86:
YY_RULE_SETUP
#line 545 "scanner.l"
{*string_buf_ptr = '\0'; BEGIN(INITIAL); return STRING;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 546 "scanner.l"
{}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 547 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 548 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 549 "scanner.l"
{*string_buf_ptr++ = '\t';}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 550 "scanner.l"
{*string_buf_ptr++ = '\r';}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 551 "scanner.l"
{*string_buf_ptr++ = '\b';}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 552 "scanner.l"
{*string_buf_ptr++ = '\f';}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 553 "scanner.l"
{
        char *yptr = yytext;
        while ( *yptr )
            *string_buf_ptr++ = *yptr++;        
    }
	YY_BREAK

case 95:
YY_RULE_SETUP
#line 560 "scanner.l"
{printf("error in %d is %s",yylineno,yytext);}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 562 "scanner.l"
ECHO;
	YY_BREAK
#line 1890 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 351 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 351 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 350);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 562 "scanner.l"
