/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 102
#define YY_END_OF_BUFFER 103
static yyconst short int yy_acclist[379] =
    {   0,
      103,  101,  102,    5,  101,  102,    3,  102,   59,  101,
      102,   10,  101,  102,   12,  101,  102,   70,  101,  102,
       13,  101,  102,   13,  101,  102,    8,  101,  102,   12,
      101,  102,    8,  101,  102,   53,  101,  102,    8,  101,
      102,   24,  101,  102,   11,  101,  102,   25,  101,  102,
        7,  101,  102,   52,  101,  102,   52,  101,  102,   52,
      101,  102,   52,  101,  102,   13,  101,  102,  101,  102,
       12,   52,  101,  102,   52,  101,  102,   52,  101,  102,
       52,  101,  102,   52,  101,  102,   52,  101,  102,   52,
      101,  102,   52,  101,  102,   52,  101,  102,   52,  101,

      102,   52,  101,  102,   52,  101,  102,   52,  101,  102,
       52,  101,  102,   52,  101,  102,   52,  101,  102,   52,
      101,  102,   52,  101,  102,   52,  101,  102,   69,  102,
       62,  102,   60,  102,  102,   80,  102,   73,  102,   71,
      102,  102,   90,  102,   84,  102,  102,  102,  102,  100,
      102,   94,  102,  102,  102,   55,  102,   57,  102,   56,
      102,   58,  102,    2,    4,   10,   53,   26,   28,   27,
        7,   52,   52,   52,   52,    6,   52,   41,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   15,   52,   52,   31,   52,   52,   52,   52,

       52,   52,   48,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   69,   61,   68,   66,   67,   63,   65,
       64,   80,   72,   79,   77,   78,   74,   76,   75,   90,
       83,   88,   89,   85,   87,   86,  100,   93,   98,   99,
       95,   97,   96,    4,   54,    1,   52,   52,   52,    9,
       49,   52,   52,   52,   52,   52,   52,   52,   14,   52,
       52,   52,   52,   52,   52,   30,   52,   52,   52,   52,
       52,   42,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   44,   52,   36,   52,   52,   52,   52,   82,
       92,   91,   81,   52,   50,   52,   52,   45,   52,   52,

       39,   52,   52,   52,   16,   52,   17,   52,   52,   52,
       52,   52,   52,   52,   52,   46,   52,   52,   52,   47,
       52,   52,   52,   52,   52,   52,   40,   52,   52,   51,
       52,    9,    9,   52,   18,   52,   35,   52,   52,   52,
       52,   43,   52,   52,   52,   34,   52,   52,   38,   52,
       52,   33,   52,   32,   52,   52,   29,   52,   22,   52,
       10,   52,   37,   52,   52,   20,   52,   52,   23,   52,
        4,   52,   52,   19,   52,   21,   52,    9
    } ;

static yyconst short int yy_accept[361] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        4,    7,    9,   12,   15,   18,   21,   24,   27,   30,
       33,   36,   39,   42,   45,   48,   51,   54,   57,   60,
       63,   66,   69,   71,   75,   78,   81,   84,   87,   90,
       93,   96,   99,  102,  105,  108,  111,  114,  117,  120,
      123,  126,  129,  131,  133,  135,  136,  138,  140,  142,
      143,  145,  147,  148,  149,  150,  152,  154,  155,  156,
      158,  160,  162,  164,  165,  165,  166,  166,  166,  167,
      167,  167,  167,  168,  168,  168,  169,  169,  170,  171,

      172,  173,  174,  175,  176,  176,  176,  176,  176,  176,
      177,  178,  180,  181,  182,  183,  184,  185,  186,  187,
      188,  189,  190,  191,  192,  193,  195,  196,  198,  199,
      200,  201,  202,  203,  205,  206,  207,  208,  209,  210,
      211,  212,  213,  214,  215,  216,  217,  218,  219,  220,
      221,  222,  223,  224,  225,  226,  227,  228,  229,  230,
      231,  231,  232,  233,  234,  235,  236,  237,  238,  238,
      239,  240,  241,  242,  243,  244,  244,  245,  245,  245,
      245,  245,  245,  246,  247,  248,  249,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  251,  251,  253,  254,

      255,  256,  257,  258,  259,  261,  262,  263,  264,  265,
      266,  268,  269,  270,  270,  271,  272,  274,  275,  276,
      277,  278,  279,  280,  281,  282,  283,  285,  287,  288,
      289,  290,  291,  292,  292,  292,  292,  292,  292,  292,
      293,  294,  295,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  298,  300,  301,  303,  304,
      305,  307,  309,  310,  311,  312,  313,  314,  315,  316,
      318,  319,  320,  322,  323,  324,  325,  326,  327,  329,
      330,  330,  330,  330,  330,  330,  330,  332,  332,  333,
      333,  334,  335,  337,  339,  340,  341,  342,  344,  345,

      346,  348,  349,  351,  352,  354,  356,  357,  359,  361,
      361,  361,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  363,  365,  366,  368,  369,
      371,  372,  372,  372,  372,  372,  372,  372,  373,  374,
      374,  374,  374,  374,  374,  374,  376,  378,  378,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    1,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       18,   17,   17,   17,   17,   17,   17,   19,   20,   21,
       22,   23,    1,   24,   25,   25,   25,   25,   25,   26,
       25,   25,   25,   25,   25,   25,   25,   27,   25,   25,
       25,   25,   25,   28,   25,   25,   25,   25,   25,   25,
       29,   30,   31,    1,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   25,   42,   43,   44,   45,
       46,   47,   25,   48,   49,   50,   51,   25,   52,   53,
       54,   25,   55,   56,   57,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[58] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    1,
        1,    1,    5,    6,    1,    1,    7,    8,    1,    1,
        1,    1,    1,    1,    7,    7,    7,    7,    1,    9,
        5,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,   10,    1,   10
    } ;

static yyconst short int yy_base[385] =
    {   0,
        0,    0,   55,   56,   59,   60,   61,   67,   74,   75,
     1101, 1100, 1099, 1098, 1097, 1096, 1095, 1094, 1097, 1106,
     1106,   94, 1091,    0, 1106, 1087,   66, 1106,   68,   64,
     1106,   91, 1091, 1071,  111, 1070,    0,    0, 1058, 1044,
     1041,  106, 1085,    0,   38,   55,   79, 1050,   41,   93,
     1043,   99,   77, 1052, 1038, 1035,   94,   84, 1032, 1033,
      105, 1039,    0, 1106, 1106,  123,    0, 1106, 1106,  132,
        0, 1106, 1106, 1071,  147,    0, 1106, 1073,  153, 1106,
     1106, 1106, 1106,  145, 1072,    0, 1068, 1070,    0, 1066,
     1068, 1064,  136,  141,  158, 1106,  170, 1106, 1106,    0,

        0, 1028, 1004,  989,  133,  156,  166,  187,  163, 1106,
      975,  953,  946,  925,  907,  922,  907,  150,  158,  912,
      901,  899,  894,  891,  889,  928,  879,  161,  921,  876,
      858,  847,  164,  839,  792,  799,  165,  789,  790,  783,
      795,  785,  797,    0, 1106, 1106, 1106, 1106, 1106, 1106,
     1106,    0, 1106, 1106, 1106, 1106, 1106, 1106, 1106,    0,
      825, 1106, 1106, 1106, 1106, 1106, 1106,    0,  823, 1106,
     1106, 1106, 1106, 1106, 1106,  821,    0,  817,  819,  815,
      816,  810,  172,  165,  708,  719,  718,  191,  207,  210,
      209,  211,  219,  227,  208, 1106,  203,  750,  716,  709,

      711,  705,  691,  687,  731,  696,  694,  691,  690,  629,
      657,  616,  625,  147,  611,  605,    0,  619,  602,  614,
      605,  598,  595,  590,  585,  572,    0,  616,  568,  570,
      497, 1106, 1106,  534,  530,  532,  531,  527,  526, 1106,
     1106,  496,  528,  215,  218,  224,  247,  228,  243,  254,
      261,  238,  251,  254,  483,    0,  488,    0,  478,  484,
      519,  518,  474,  477,  409,  425,  409,  406,  414,    0,
      406,  398,  436,  389,  401,  395,  317,  327,  359,  326,
      356,  355,  351,  350,  352,  348,  351,  285,  338,  368,
      252,  304,  349,  348,  306,  300,  305,    0,  304,  296,

        0,  312,    0,  248,    0,    0,  235,  272,  266,  259,
      255, 1106,    0,  421,  423,  424,  430,  461,    0,  425,
      336,  419,  511,  542,  210,  249,  193,  229,  197,  175,
     1106,  595,  599,  596,    0,  598,    0,   70,   52,  600,
      604,  614,  628,  633,  624,   84,   61,  664,  613,    0,
      717,  719,  721,  728,  759,  812,    0,  814, 1106,  845,
      855,  865,  875,  885,  895,  905,  909,  915,  923,  933,
      943,  953,  960,  970,  980,  986,  994, 1003, 1012, 1022,
     1032, 1041, 1050, 1060
    } ;

static yyconst short int yy_def[385] =
    {   0,
      359,    1,  360,  360,  361,  361,  362,  362,  363,  363,
      364,  364,  364,  364,  364,  364,  364,  364,  359,  359,
      359,  359,  359,  365,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  366,  367,  367,  367,
      367,  368,  359,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  369,  359,  359,  359,  370,  359,  359,  359,
      371,  359,  359,  359,  359,  372,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  373,  359,  359,  365,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  366,

      367,  367,  367,  367,  374,  375,  359,  359,  376,  359,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  369,  359,  359,  359,  359,  359,  359,
      359,  370,  359,  359,  359,  359,  359,  359,  359,  371,
      359,  359,  359,  359,  359,  359,  359,  372,  359,  359,
      359,  359,  359,  359,  359,  359,  373,  359,  377,  378,
      359,  359,  359,  359,  367,  367,  367,  374,  359,  379,
      375,  359,  380,  368,  359,  359,  376,  367,  367,  367,

      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  359,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  359,  359,  381,  382,  377,  359,  378,  359,  359,
      359,  367,  367,  359,  374,  374,  379,  375,  375,  380,
      368,  374,  375,  359,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      381,  359,  382,  359,  359,  359,  367,  359,  374,  359,
      375,  367,  367,  367,  367,  367,  367,  367,  367,  367,

      367,  367,  367,  367,  367,  367,  367,  367,  367,  359,
      359,  359,  288,  374,  383,  374,  374,  359,  290,  383,
      375,  375,  375,  359,  367,  367,  367,  367,  367,  367,
      359,  383,  384,  374,  318,  375,  324,  367,  367,  383,
      383,  383,  384,  374,  375,  367,  367,  359,  383,  348,
      383,  383,  383,  383,  359,  383,  355,  383,    0,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359
    } ;

static yyconst short int yy_nxt[1164] =
    {   0,
       20,   21,   22,   21,   23,   24,   25,   26,   27,   28,
       25,   25,   29,   30,   31,   25,   32,   32,   33,   31,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       28,   44,   45,   46,   47,   48,   49,   50,   51,   38,
       52,   38,   53,   54,   55,   56,   57,   58,   59,   60,
       38,   61,   38,   62,   27,   25,   28,   64,   64,   65,
       65,   68,   68,   72,  214,   73,   69,   69,   74,   72,
       91,   73,   91,   92,   74,   92,   77,   77,   78,   78,
       93,   93,  111,  119,   66,   66,  112,  214,   70,   70,
       75,   73,   73,  120,  347,   84,   75,   84,   85,   86,

      113,   87,  114,   79,   79,   94,  346,   93,   93,  130,
      105,  115,   97,  106,   97,   91,  137,  131,   92,  107,
      138,  116,  108,  108,  117,  145,  135,  146,   73,   73,
       73,   73,   98,  121,  153,  122,  126,  189,  123,  154,
      124,  136,  127,  128,  141,  142,   84,  129,   84,  162,
       94,   91,   93,   93,   92,  170,  147,  183,  183,  184,
      148,  184,  190,  192,  214,  155,  184,  149,  184,  156,
      150,   97,  151,   97,   91,  194,  157,   92,  214,  158,
      163,  159,  108,  108,  164,  193,  171,  205,  183,  183,
      172,  165,  129,  196,  166,  244,  167,  173,  206,  194,

      174,  195,  175,  108,  108,  224,  207,  216,  221,  225,
      217,  240,  188,  129,  246,  194,  244,  196,  241,  194,
      190,  191,  244,  194,  254,  254,  249,  194,  244,  339,
      251,  252,  214,  196,  253,  244,  288,  196,  193,  247,
      107,  196,  244,  108,  108,  196,  129,  190,  250,  188,
      244,  246,  214,  190,  289,  290,  191,  193,  244,  244,
      338,  249,  331,  331,  251,  252,  194,  190,  253,  214,
      254,  254,  193,  291,  107,  214,  247,  108,  108,  330,
      193,  193,  329,  250,  196,  188,  188,  188,  313,  314,
      188,  188,  315,  188,  188,  188,  188,  188,  316,  188,

      188,  317,  317,  188,  188,  188,  188,  188,  188,  318,
      318,  318,  318,  188,  190,  188,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  188,
      188,  188,  244,  244,  129,  129,  328,  327,  290,  326,
      325,  214,  214,  129,  214,  312,  312,  311,  284,  310,
      282,  309,  214,  308,  307,  193,  291,  190,  191,  191,
      191,  319,  320,  191,  191,  321,  191,  191,  191,  191,
      191,  322,  191,  191,  323,  323,  191,  191,  191,  191,
      191,  191,  324,  324,  324,  324,  191,  193,  191,  324,

      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  191,  191,  191,  244,  244,  249,  244,  249,
      246,  306,  246,  288,  244,  323,  323,  129,  305,  214,
      317,  317,  288,  304,  334,  303,  317,  317,  193,  302,
      190,  289,  333,  190,  333,  301,  300,  299,  298,  190,
      289,  188,  188,  188,  188,  244,  188,  188,  188,  188,
      188,  188,  188,  288,  188,  188,  188,  335,  335,  188,
      188,  188,  188,  188,  188,  335,  335,  335,  335,  188,
      190,  289,  335,  335,  335,  335,  335,  335,  335,  335,

      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  188,  188,  188,  244,  297,
      296,  214,  214,  290,  295,  336,  294,  323,  323,  293,
      292,  214,  287,  286,  239,  285,  237,  284,  282,  280,
      193,  291,  191,  191,  191,  191,  191,  191,  191,  244,
      191,  191,  191,  191,  290,  191,  191,  191,  337,  337,
      191,  191,  191,  191,  191,  191,  337,  337,  337,  337,
      191,  193,  291,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  191,  191,  191,  249,

      244,  332,  246,  341,  249,  244,  342,  246,  249,  279,
      278,  246,  344,  344,  345,  345,  348,  249,  249,  214,
      246,  246,  277,  276,  333,  190,  348,  193,  343,  333,
      332,  244,  341,  333,  349,  342,  290,  244,  275,  274,
      345,  345,  333,  333,  349,  288,  273,  272,  271,  344,
      344,  270,  269,  193,  291,  268,  267,  343,  266,  129,
      214,  265,  190,  289,  332,  332,  332,  350,  351,  332,
      332,  352,  332,  332,  332,  332,  332,  353,  332,  332,
      354,  354,  332,  332,  332,  332,  332,  332,  355,  355,
      355,  355,  332,  333,  332,  355,  355,  355,  355,  355,

      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  332,  332,
      332,  249,  264,  249,  246,  249,  246,  263,  246,  348,
      262,  348,  249,  261,  214,  246,  260,  354,  354,  259,
      348,  258,  356,  257,  354,  354,  333,  349,  333,  349,
      333,  256,  255,  214,  243,  129,  242,  333,  349,  332,
      332,  332,  332,  249,  332,  332,  246,  332,  332,  332,
      332,  348,  332,  332,  332,  357,  357,  332,  332,  332,
      332,  332,  332,  357,  357,  357,  357,  332,  333,  349,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,

      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  332,  332,  332,  249,  241,  249,  246,
      240,  246,  239,  237,  235,  234,  348,  233,  358,  358,
      358,  358,  232,  231,  230,  229,  228,  227,  226,  223,
      222,  333,  214,  333,  349,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   89,  220,   89,   89,   89,

       89,   89,   89,   89,   89,  100,  219,  100,  100,  100,
      100,  100,  100,  100,  100,  101,  101,  109,  109,  218,
      109,  109,  109,  144,  214,  215,  144,  144,  144,  144,
      144,  214,  144,  152,  213,  152,  212,  152,  152,  152,
      152,  211,  152,  160,  210,  209,  208,  160,  160,  160,
      160,  204,  160,  168,  203,  202,  168,  168,  168,  168,
      177,  201,  177,  177,  177,  177,  177,  177,  177,  177,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      197,  200,  197,  197,  236,  236,  236,  236,  236,  236,

      236,  199,  236,  238,  238,  238,  238,  238,  238,  238,
      198,  238,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  281,  281,  281,  281,  281,  281,  281,  187,
      281,  283,  283,  283,  283,  283,  283,  283,  186,  283,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      185,  182,  181,  180,  179,  178,  176,  169,  161,  143,
      140,  139,  134,  133,  132,  125,  118,  110,  104,  103,
      102,   99,   96,   95,   90,   88,  359,   83,   83,   82,

       82,   81,   81,   80,   80,   19,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359
    } ;

static yyconst short int yy_chk[1164] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    3,
        4,    5,    6,    7,  347,    7,    5,    6,    7,    8,
       27,    8,   29,   27,    8,   29,    9,   10,    9,   10,
       30,   30,   45,   49,    3,    4,   45,  346,    5,    6,
        7,    9,   10,   49,  339,   22,    8,   22,   22,   22,

       46,   22,   46,    9,   10,   32,  338,   32,   32,   53,
       42,   47,   35,   42,   35,   35,   58,   53,   35,   42,
       58,   47,   42,   42,   47,   66,   57,   66,    9,   10,
        9,   10,   35,   50,   70,   50,   52,  105,   50,   70,
       50,   57,   52,   52,   61,   61,   84,   52,   84,   75,
       93,  214,   93,   93,  214,   79,   66,   94,   94,   95,
       66,   95,  105,  106,  128,   70,  184,   66,  184,   70,
       66,   97,   66,   97,   97,  109,   70,   97,  330,   70,
       75,   70,  107,  107,   75,  106,   79,  118,  183,  183,
       79,   75,  118,  109,   75,  188,   75,   79,  119,  108,

       79,  108,   79,  108,  108,  137,  119,  128,  133,  137,
      128,  189,  190,  133,  190,  197,  191,  108,  192,  189,
      188,  193,  245,  192,  195,  195,  193,  244,  246,  329,
      194,  194,  328,  197,  194,  248,  246,  189,  191,  190,
      194,  192,  252,  194,  194,  244,  327,  245,  193,  247,
      249,  247,  326,  246,  246,  249,  250,  248,  253,  291,
      325,  250,  311,  310,  251,  251,  254,  252,  251,  309,
      254,  254,  249,  249,  251,  308,  247,  251,  251,  307,
      253,  291,  304,  250,  254,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,

      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  289,  321,  302,  300,  299,  297,  321,  296,
      295,  294,  293,  292,  287,  286,  285,  284,  283,  282,
      281,  280,  279,  278,  277,  321,  321,  289,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,

      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  314,  322,  315,  316,  320,
      315,  276,  320,  314,  317,  322,  322,  275,  274,  273,
      316,  316,  317,  272,  317,  271,  317,  317,  322,  269,
      314,  314,  315,  316,  320,  268,  267,  266,  265,  317,
      317,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,

      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  323,  264,
      263,  262,  261,  323,  260,  323,  259,  323,  323,  257,
      255,  243,  242,  239,  238,  237,  236,  235,  234,  231,
      323,  323,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  332,

      334,  333,  332,  333,  340,  336,  333,  340,  341,  230,
      229,  341,  334,  334,  336,  336,  341,  349,  342,  228,
      349,  342,  226,  225,  332,  334,  342,  336,  333,  340,
      343,  345,  343,  341,  341,  343,  345,  344,  224,  223,
      345,  345,  349,  342,  342,  344,  222,  221,  220,  344,
      344,  219,  218,  345,  345,  216,  215,  343,  213,  212,
      211,  210,  344,  344,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,

      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  351,  209,  352,  351,  353,  352,  208,  353,  351,
      207,  352,  354,  206,  205,  354,  204,  353,  353,  203,
      354,  202,  354,  201,  354,  354,  351,  351,  352,  352,
      353,  200,  199,  198,  187,  186,  185,  354,  354,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,

      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  356,  182,  358,  356,
      181,  358,  180,  179,  178,  176,  358,  169,  356,  356,
      358,  358,  161,  143,  142,  141,  140,  139,  138,  136,
      135,  356,  134,  358,  358,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  365,  132,  365,  365,  365,

      365,  365,  365,  365,  365,  366,  131,  366,  366,  366,
      366,  366,  366,  366,  366,  367,  367,  368,  368,  130,
      368,  368,  368,  369,  129,  127,  369,  369,  369,  369,
      369,  126,  369,  370,  125,  370,  124,  370,  370,  370,
      370,  123,  370,  371,  122,  121,  120,  371,  371,  371,
      371,  117,  371,  372,  116,  115,  372,  372,  372,  372,
      373,  114,  373,  373,  373,  373,  373,  373,  373,  373,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      376,  113,  376,  376,  377,  377,  377,  377,  377,  377,

      377,  112,  377,  378,  378,  378,  378,  378,  378,  378,
      111,  378,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  381,  381,  381,  381,  381,  381,  381,  104,
      381,  382,  382,  382,  382,  382,  382,  382,  103,  382,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      102,   92,   91,   90,   88,   87,   85,   78,   74,   62,
       60,   59,   56,   55,   54,   51,   48,   43,   41,   40,
       39,   36,   34,   33,   26,   23,   19,   18,   17,   16,

       15,   14,   13,   12,   11,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#define INITIAL 0
#line 2 "scanner.l"
    #include <stdio.h>
    #include <ctype.h>
    #include <stdlib.h>
    #include <string.h>
    #include "parser.tab.h"

    #pragma warning (disable: 4005)
    #include "parser.hpp"
    #include "astNodes.hpp"
    using namespace std;

    #define Stack_SIZE 100
    void push();
    void pop();
    void show();

    int top = -1;
    int stack_arr[Stack_SIZE];

    void push(int insert_item)
    {
        if (top == Stack_SIZE - 1)
            printf("\nOverflow!!");

        else
        {
            top++;
            stack_arr[top] = insert_item;
        }
    }

    void pop()
    {
        if (top == -1)
            printf("\nUnderflow!!");

        else
            top--;
    }

    void stackshow()
    {
        if (top == -1)
            printf("\nUnderflow!!");

        else
        {
            printf("\nElements present in the stack: \n");
            for (int i = top; i >= 0; --i)
                printf("%d\n", stack_arr[i]);
        }
    } 

    #define keyword_size 10
    char keyword[keyword_size];

    #define MAX_STR_CONST 256
    char string_buf[MAX_STR_CONST];
    char *string_buf_ptr;

    int current_indentation = 0;
    int spaces = 0;

    extern YYSTYPE yylval;
#define DOUBLE_STRING 1

#define SINGLE_STRING 2

#define COMMENT_STRING 3

#define COMMENT_STRING_DOUBLE 4

#define INDENTSTATE 5

#define DEDENTALLSTATE 6

#define DEDENTSTATE 7

#define NEWNEW 8

#line 878 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 118 "scanner.l"


#line 1032 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 360 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1106 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 120 "scanner.l"
{
                            BEGIN(INDENTSTATE);
                            if(top < 0)
                                push(0);

                            spaces = 0;
                            for(int i = 0; i < yyleng; i++){
                                if (yytext[i] == ' ') {
                                    spaces++;
                                } else if (yytext[i] == '\t') {
                                    spaces += 8;
                                }
                            }
                            push(spaces);

                            current_indentation = spaces;
                            unput(' ');

                            return NEWLINE;
                        }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 141 "scanner.l"
{
                            if(top < 0)
                                push(0);

                            spaces = 0;
                            for(int i = 0; i < yyleng; i++){
                                if (yytext[i] == ' ') {
                                    spaces++;
                                } else if (yytext[i] == '\t') {
                                    spaces += 8;
                                }
                            }
                            current_indentation = spaces;

                            unput(' ');
                            BEGIN(DEDENTSTATE);
                            return NEWLINE;
                        }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 160 "scanner.l"
{ 
                            BEGIN(DEDENTALLSTATE);
                            unput(' ');
                            return NEWLINE;
                        }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 166 "scanner.l"
{}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(DOUBLE_STRING):
case YY_STATE_EOF(SINGLE_STRING):
case YY_STATE_EOF(COMMENT_STRING):
case YY_STATE_EOF(COMMENT_STRING_DOUBLE):
case YY_STATE_EOF(INDENTSTATE):
case YY_STATE_EOF(DEDENTALLSTATE):
case YY_STATE_EOF(DEDENTSTATE):
case YY_STATE_EOF(NEWNEW):
#line 168 "scanner.l"
{
                    BEGIN(NEWNEW);
                    unput(' ');

                    if(stack_arr[top] == 0)
                        return 0;
                }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 177 "scanner.l"
{}
	YY_BREAK
case 6:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 179 "scanner.l"
{}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 181 "scanner.l"
{}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 183 "scanner.l"
{yylval.strval = strdup(yytext); return yytext[0];}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 185 "scanner.l"
{return ARRAY;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 187 "scanner.l"
{}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 189 "scanner.l"
{yylval.strval = strdup(yytext); return yytext[0];}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 191 "scanner.l"
{yylval.strval = strdup(yytext); return yytext[0];}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 193 "scanner.l"
{yylval.strval = strdup(yytext); return yytext[0];} 
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 195 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return DEF;
                        }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 200 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return IF;
                        }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 205 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return ELIF;
                        }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 210 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return ELSE;
                        }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 215 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return BREAK;
                        }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 220 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return CONTINUE;
                        }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 225 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return GLOBAL;
                        }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 230 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return NONLOCAL;
                        }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 235 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return YIELD;
                        }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 240 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return RETURN;
                        }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 245 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return LT;
                        }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 250 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return GT;
                        }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 255 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return LTE;
                        }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 260 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return GTE;
                        }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 265 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return EQUAL;
                        }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 270 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return WHILE;
                        }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 275 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return FOR;
                        }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 280 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return IN;
                        }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 285 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return RANGE;
                        }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 290 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return PRINT;
                        }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 295 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return INPUT;
                        }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 300 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return CLASS;
                        }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 305 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return TRY;
                        }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 310 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return EXCEPT;
                        }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 315 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return MATCH;
                        }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 320 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return CASE;
                        }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 325 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return WITH;
                        }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 330 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return AS;
                        }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 335 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return INT;
                        }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 340 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return FLOAT;
                        }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 345 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return STR;
                        }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 350 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return BOOL;
                        }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 355 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return LIST;
                        }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 360 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return PASS;
                        }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 365 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return OR;
                        }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 370 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return AND;
                        }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 375 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return TRUE_TOK;
                        }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 380 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return FALSE_TOK;
                        }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 386 "scanner.l"
{
                            yylval.astNode = new IdentifierNode("IDENTIFIER", "Identifier", yytext);
                            return ID;
                        }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 391 "scanner.l"
{
                            yylval.astNode = new NumberNode("INT", "int", atoi(yytext));
                            return INT_NUMBER;
                        }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 396 "scanner.l"
{
                            yylval.astNode = new NumberNode("FLOAT", "float", atoi(yytext));
                            return FLOAT_NUMBER;
                        }
	YY_BREAK

case 55:
YY_RULE_SETUP
#line 403 "scanner.l"
{
        BEGIN(INITIAL);
        return INDENT;
    }
	YY_BREAK


case 56:
YY_RULE_SETUP
#line 410 "scanner.l"
{

        int flag = 1;
        for (int i = 0; i <= top; i++) {
            if (current_indentation == stack_arr[i])
                flag = 0;
        }

        if(flag)
            return INDENTERROR;

        int end = 1;
        while(current_indentation < stack_arr[top])
        {
            unput(' ');
            BEGIN(DEDENTSTATE);
            end = 0;
            pop();

            return DEDENT;
        }

        if(end)
            BEGIN(INITIAL);

    }
	YY_BREAK


case 57:
YY_RULE_SETUP
#line 439 "scanner.l"
{
        if (top < 0)
            push(0);

        if (stack_arr[top] > 0) {
            while (top > 0) {
                unput(' ');
                BEGIN(DEDENTALLSTATE);
                pop();

                return DEDENT;
            }
        } else {
            BEGIN(INITIAL);
        }
    }
	YY_BREAK


case 58:
YY_RULE_SETUP
#line 458 "scanner.l"
{
        BEGIN(DEDENTALLSTATE);
        unput(' ');
        return NEWLINE;
    }
	YY_BREAK

case 59:
YY_RULE_SETUP
#line 466 "scanner.l"
{ string_buf_ptr = string_buf; BEGIN(DOUBLE_STRING); }    
	YY_BREAK

case 60:
YY_RULE_SETUP
#line 469 "scanner.l"
{*string_buf_ptr = '\0'; BEGIN(INITIAL); yylval.astNode = new StringNode("STRING", "string", string_buf); return STRING;} 
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 470 "scanner.l"
{              }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 471 "scanner.l"
{printf("error in line %d\n", yylineno); BEGIN(INITIAL);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 472 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 473 "scanner.l"
{*string_buf_ptr++ = '\t';}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 474 "scanner.l"
{*string_buf_ptr++ = '\r';}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 475 "scanner.l"
{*string_buf_ptr++ = '\b';}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 476 "scanner.l"
{*string_buf_ptr++ = '\f';}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 477 "scanner.l"
{*string_buf_ptr++ = '\"';} 
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 478 "scanner.l"
{
        char *yptr = yytext;
        while ( *yptr )
            *string_buf_ptr++ = *yptr++;        
    }
	YY_BREAK

case 70:
YY_RULE_SETUP
#line 485 "scanner.l"
{ string_buf_ptr = string_buf; BEGIN(SINGLE_STRING); }    
	YY_BREAK

case 71:
YY_RULE_SETUP
#line 487 "scanner.l"
{*string_buf_ptr = '\0'; BEGIN(INITIAL); yylval.astNode = new StringNode("STRING", "string", string_buf); return STRING;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 488 "scanner.l"
{              }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 489 "scanner.l"
{printf("line%d, ERROR: new line in string\n", yylineno); BEGIN(INITIAL);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 490 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 491 "scanner.l"
{*string_buf_ptr++ = '\t';}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 492 "scanner.l"
{*string_buf_ptr++ = '\r';}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 493 "scanner.l"
{*string_buf_ptr++ = '\b';}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 494 "scanner.l"
{*string_buf_ptr++ = '\f';}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 495 "scanner.l"
{*string_buf_ptr++ = '\'';} 
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 496 "scanner.l"
{
        char *yptr = yytext;
        while ( *yptr )
            *string_buf_ptr++ = *yptr++;        
    }
	YY_BREAK

case 81:
YY_RULE_SETUP
#line 503 "scanner.l"
{   
                            int i = 0;
                            strcpy(keyword, " ");

                            while(yytext[i] != ' ') {
                                if (yytext[i] == '\'') 
                                    break;

                                keyword[i] = yytext[i];
                                i++;
                            }

                            string_buf_ptr = string_buf; BEGIN(COMMENT_STRING); 

                            if (strcmp(keyword, "=") == 0) {
                                return yytext[0];
                            }
                            else if (strcmp(keyword, "(") == 0 || strcmp(keyword, "{") == 0 || strcmp(keyword, "[") == 0) {
                                return yytext[0];
                            }

                            else {
                                if ( strcmp(keyword, "return") == 0) {
                                    return RETURN;
                                }
                            }

                            
                        }
	YY_BREAK

case 82:
YY_RULE_SETUP
#line 534 "scanner.l"
{*string_buf_ptr = '\0'; BEGIN(INITIAL); yylval.astNode = new StringNode("STRING", "string", string_buf); return STRING;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 535 "scanner.l"
{}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 536 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 537 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 538 "scanner.l"
{*string_buf_ptr++ = '\t';}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 539 "scanner.l"
{*string_buf_ptr++ = '\r';}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 540 "scanner.l"
{*string_buf_ptr++ = '\b';}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 541 "scanner.l"
{*string_buf_ptr++ = '\f';}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 542 "scanner.l"
{
        char *yptr = yytext;
        while ( *yptr )
            *string_buf_ptr++ = *yptr++;        
    }
	YY_BREAK

case 91:
YY_RULE_SETUP
#line 549 "scanner.l"
{   
                            int i = 0;
                            strcpy(keyword, " ");

                            while(yytext[i] != ' ') {
                                if (yytext[i] == '\"') 
                                    break;

                                keyword[i] = yytext[i];
                                i++;
                            }

                            string_buf_ptr = string_buf; BEGIN(COMMENT_STRING_DOUBLE); 

                            if (strcmp(keyword, "=") == 0) {
                                return yytext[0];
                            }

                            else if (strcmp(keyword, "(") == 0 || strcmp(keyword, "{") == 0 || strcmp(keyword, "[") == 0) {
                                return yytext[0];
                            }

                            else {
                                if ( strcmp(keyword, "return") == 0) {
                                    return RETURN;
                                }
                            }
                            
                        }
	YY_BREAK

case 92:
YY_RULE_SETUP
#line 580 "scanner.l"
{*string_buf_ptr = '\0'; BEGIN(INITIAL); yylval.astNode = new StringNode("STRING", "string", string_buf); return STRING;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 581 "scanner.l"
{}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 582 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 583 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 584 "scanner.l"
{*string_buf_ptr++ = '\t';}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 585 "scanner.l"
{*string_buf_ptr++ = '\r';}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 586 "scanner.l"
{*string_buf_ptr++ = '\b';}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 587 "scanner.l"
{*string_buf_ptr++ = '\f';}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 588 "scanner.l"
{
        char *yptr = yytext;
        while ( *yptr )
            *string_buf_ptr++ = *yptr++;        
    }
	YY_BREAK

case 101:
YY_RULE_SETUP
#line 595 "scanner.l"
{printf("error in %d is %s",yylineno,yytext);}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 597 "scanner.l"
ECHO;
	YY_BREAK
#line 1952 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 360 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 360 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 359);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 597 "scanner.l"
