#line 1 "scanner.cpp"

#line 3 "scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 3
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    #define yy_create_buffer yy_create_buffer

    #define yy_delete_buffer yy_delete_buffer

    #define yy_scan_buffer yy_scan_buffer

    #define yy_scan_string yy_scan_string

    #define yy_scan_bytes yy_scan_bytes

    #define yy_init_buffer yy_init_buffer

    #define yy_flush_buffer yy_flush_buffer

    #define yy_load_buffer_state yy_load_buffer_state

    #define yy_switch_to_buffer yy_switch_to_buffer

    #define yypush_buffer_state yypush_buffer_state

    #define yypop_buffer_state yypop_buffer_state

    #define yyensure_buffer_stack yyensure_buffer_stack

    #define yylex yylex

    #define yyrestart yyrestart

    #define yylex_init yylex_init

    #define yylex_init_extra yylex_init_extra

    #define yylex_destroy yylex_destroy

    #define yyget_debug yyget_debug

    #define yyset_debug yyset_debug

    #define yyget_extra yyget_extra

    #define yyset_extra yyset_extra

    #define yyget_in yyget_in

    #define yyset_in yyset_in

    #define yyget_out yyget_out

    #define yyset_out yyset_out

    #define yyget_leng yyget_leng

    #define yyget_text yyget_text

    #define yyget_lineno yyget_lineno

    #define yyset_lineno yyset_lineno

    #define yywrap yywrap

    #define yyalloc yyalloc

    #define yyrealloc yyrealloc

    #define yyfree yyfree

    #define yytext yytext

    #define yyleng yyleng

    #define yyin yyin

    #define yyout yyout

    #define yy_flex_debug yy_flex_debug

    #define yylineno yylineno

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 102
#define YY_END_OF_BUFFER 103
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[360] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  103,  101,
        5,    3,   59,   10,   12,   70,   13,   13,    8,   12,
        8,   53,    8,   24,   11,   25,    7,   52,   52,   52,
       52,   13,  101,   12,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   69,   62,   60,  102,   80,   73,   71,  102,
       90,   84,  102,  102,  102,  100,   94,  102,  102,   55,
       57,   56,   58,    2,    0,    4,    0,    0,   10,    0,
        0,    0,   53,    0,    0,   26,    0,   28,   27,    7,

       52,   52,   52,   52,    0,    0,    0,    0,    0,    6,
       52,   41,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   15,   52,   31,   52,   52,
       52,   52,   52,   48,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   69,   61,   68,   66,   67,   63,   65,
       64,   80,   72,   79,   77,   78,   74,   76,   75,   90,
        0,   83,   88,   89,   85,   87,   86,  100,    0,   93,
       98,   99,   95,   97,   96,    0,    4,    0,    0,    0,
        0,    0,   54,    1,   52,   52,   52,    0,    0,    0,
        0,    0,    0,    0,    0,    9,    0,   49,   52,   52,

       52,   52,   52,   52,   14,   52,   52,   52,   52,   52,
       30,   52,   52,    0,   52,   52,   42,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   44,   36,   52,   52,
       52,   82,   92,    0,    0,    0,    0,    0,    0,   91,
       81,   52,   50,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   52,   45,   52,   39,   52,   52,
       16,   17,   52,   52,   52,   52,   52,   52,   52,   46,
       52,   52,   47,   52,   52,   52,   52,   52,   40,   52,
        0,    0,    0,    0,    0,    0,   51,    0,    9,    0,
        9,   52,   18,   35,   52,   52,   52,   43,   52,   52,

       34,   52,   38,   52,   33,   32,   52,   29,   22,    0,
        0,   10,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   52,   37,   52,   20,   52,   23,
        4,    0,    0,    0,    0,    0,    0,   52,   52,    0,
        0,    0,    0,    0,    0,   19,   21,    0,    9,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    1,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       18,   17,   17,   17,   17,   17,   17,   19,   20,   21,
       22,   23,    1,   24,   25,   25,   25,   25,   25,   26,
       25,   25,   25,   25,   25,   25,   25,   27,   25,   25,
       25,   25,   25,   28,   25,   25,   25,   25,   25,   25,
       29,   30,   31,    1,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   25,   42,   43,   44,   45,
       46,   47,   25,   48,   49,   50,   51,   25,   52,   53,
       54,   25,   55,   56,   57,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[58] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    1,
        1,    1,    5,    6,    1,    1,    7,    8,    1,    1,
        1,    1,    1,    1,    7,    7,    7,    7,    1,    9,
        5,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,   10,    1,   10
    } ;

static const flex_int16_t yy_base[385] =
    {   0,
        0,    0,   55,   56,   59,   60,   61,   67,   74,   75,
     1101, 1100, 1099, 1098, 1097, 1096, 1095, 1094, 1097, 1106,
     1106,   94, 1091,    0, 1106, 1087,   66, 1106,   68,   64,
     1106,   91, 1091, 1071,  111, 1070,    0,    0, 1058, 1044,
     1041,  106, 1085,    0,   38,   55,   79, 1050,   41,   93,
     1043,   99,   77, 1052, 1038, 1035,   94,   84, 1032, 1033,
      105, 1039,    0, 1106, 1106,  123,    0, 1106, 1106,  132,
        0, 1106, 1106, 1071,  147,    0, 1106, 1073,  153, 1106,
     1106, 1106, 1106,  145, 1072,    0, 1068, 1070,    0, 1066,
     1068, 1064,  136,  141,  158, 1106,  170, 1106, 1106,    0,

        0, 1028, 1004,  989,  133,  156,  166,  187,  163, 1106,
      975,  953,  946,  925,  907,  922,  907,  150,  158,  912,
      901,  899,  894,  891,  889,  928,  879,  161,  921,  876,
      858,  847,  164,  839,  792,  799,  165,  789,  790,  783,
      795,  785,  797,    0, 1106, 1106, 1106, 1106, 1106, 1106,
     1106,    0, 1106, 1106, 1106, 1106, 1106, 1106, 1106,    0,
      825, 1106, 1106, 1106, 1106, 1106, 1106,    0,  823, 1106,
     1106, 1106, 1106, 1106, 1106,  821,    0,  817,  819,  815,
      816,  810,  172,  165,  708,  719,  718,  191,  207,  210,
      209,  211,  219,  227,  208, 1106,  203,  750,  716,  709,

      711,  705,  691,  687,  731,  696,  694,  691,  690,  629,
      657,  616,  625,  147,  611,  605,    0,  619,  602,  614,
      605,  598,  595,  590,  585,  572,    0,  616,  568,  570,
      497, 1106, 1106,  534,  530,  532,  531,  527,  526, 1106,
     1106,  496,  528,  215,  218,  224,  247,  228,  243,  254,
      261,  238,  251,  254,  483,    0,  488,    0,  478,  484,
      519,  518,  474,  477,  409,  425,  409,  406,  414,    0,
      406,  398,  436,  389,  401,  395,  317,  327,  359,  326,
      356,  355,  351,  350,  352,  348,  351,  285,  338,  368,
      252,  304,  349,  348,  306,  300,  305,    0,  304,  296,

        0,  312,    0,  248,    0,    0,  235,  272,  266,  259,
      255, 1106,    0,  421,  423,  424,  430,  461,    0,  425,
      336,  419,  511,  542,  210,  249,  193,  229,  197,  175,
     1106,  595,  599,  596,    0,  598,    0,   70,   52,  600,
      604,  614,  628,  633,  624,   84,   61,  664,  613,    0,
      717,  719,  721,  728,  759,  812,    0,  814, 1106,  845,
      855,  865,  875,  885,  895,  905,  909,  915,  923,  933,
      943,  953,  960,  970,  980,  986,  994, 1003, 1012, 1022,
     1032, 1041, 1050, 1060
    } ;

static const flex_int16_t yy_def[385] =
    {   0,
      359,    1,  360,  360,  361,  361,  362,  362,  363,  363,
      364,  364,  364,  364,  364,  364,  364,  364,  359,  359,
      359,  359,  359,  365,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  366,  367,  367,  367,
      367,  368,  359,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  369,  359,  359,  359,  370,  359,  359,  359,
      371,  359,  359,  359,  359,  372,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  373,  359,  359,  365,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  366,

      367,  367,  367,  367,  374,  375,  359,  359,  376,  359,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  369,  359,  359,  359,  359,  359,  359,
      359,  370,  359,  359,  359,  359,  359,  359,  359,  371,
      359,  359,  359,  359,  359,  359,  359,  372,  359,  359,
      359,  359,  359,  359,  359,  359,  373,  359,  377,  378,
      359,  359,  359,  359,  367,  367,  367,  374,  359,  379,
      375,  359,  380,  368,  359,  359,  376,  367,  367,  367,

      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  359,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  359,  359,  381,  382,  377,  359,  378,  359,  359,
      359,  367,  367,  359,  374,  374,  379,  375,  375,  380,
      368,  374,  375,  359,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      381,  359,  382,  359,  359,  359,  367,  359,  374,  359,
      375,  367,  367,  367,  367,  367,  367,  367,  367,  367,

      367,  367,  367,  367,  367,  367,  367,  367,  367,  359,
      359,  359,  288,  374,  383,  374,  374,  359,  290,  383,
      375,  375,  375,  359,  367,  367,  367,  367,  367,  367,
      359,  383,  384,  374,  318,  375,  324,  367,  367,  383,
      383,  383,  384,  374,  375,  367,  367,  359,  383,  348,
      383,  383,  383,  383,  359,  383,  355,  383,    0,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359
    } ;

static const flex_int16_t yy_nxt[1164] =
    {   0,
       20,   21,   22,   21,   23,   24,   25,   26,   27,   28,
       25,   25,   29,   30,   31,   25,   32,   32,   33,   31,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       28,   44,   45,   46,   47,   48,   49,   50,   51,   38,
       52,   38,   53,   54,   55,   56,   57,   58,   59,   60,
       38,   61,   38,   62,   27,   25,   28,   64,   64,   65,
       65,   68,   68,   72,  214,   73,   69,   69,   74,   72,
       91,   73,   91,   92,   74,   92,   77,   77,   78,   78,
       93,   93,  111,  119,   66,   66,  112,  214,   70,   70,
       75,   73,   73,  120,  347,   84,   75,   84,   85,   86,

      113,   87,  114,   79,   79,   94,  346,   93,   93,  130,
      105,  115,   97,  106,   97,   91,  137,  131,   92,  107,
      138,  116,  108,  108,  117,  145,  135,  146,   73,   73,
       73,   73,   98,  121,  153,  122,  126,  189,  123,  154,
      124,  136,  127,  128,  141,  142,   84,  129,   84,  162,
       94,   91,   93,   93,   92,  170,  147,  183,  183,  184,
      148,  184,  190,  192,  214,  155,  184,  149,  184,  156,
      150,   97,  151,   97,   91,  194,  157,   92,  214,  158,
      163,  159,  108,  108,  164,  193,  171,  205,  183,  183,
      172,  165,  129,  196,  166,  244,  167,  173,  206,  194,

      174,  195,  175,  108,  108,  224,  207,  216,  221,  225,
      217,  240,  188,  129,  246,  194,  244,  196,  241,  194,
      190,  191,  244,  194,  254,  254,  249,  194,  244,  339,
      251,  252,  214,  196,  253,  244,  288,  196,  193,  247,
      107,  196,  244,  108,  108,  196,  129,  190,  250,  188,
      244,  246,  214,  190,  289,  290,  191,  193,  244,  244,
      338,  249,  331,  331,  251,  252,  194,  190,  253,  214,
      254,  254,  193,  291,  107,  214,  247,  108,  108,  330,
      193,  193,  329,  250,  196,  188,  188,  188,  313,  314,
      188,  188,  315,  188,  188,  188,  188,  188,  316,  188,

      188,  317,  317,  188,  188,  188,  188,  188,  188,  318,
      318,  318,  318,  188,  190,  188,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  188,
      188,  188,  244,  244,  129,  129,  328,  327,  290,  326,
      325,  214,  214,  129,  214,  312,  312,  311,  284,  310,
      282,  309,  214,  308,  307,  193,  291,  190,  191,  191,
      191,  319,  320,  191,  191,  321,  191,  191,  191,  191,
      191,  322,  191,  191,  323,  323,  191,  191,  191,  191,
      191,  191,  324,  324,  324,  324,  191,  193,  191,  324,

      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  191,  191,  191,  244,  244,  249,  244,  249,
      246,  306,  246,  288,  244,  323,  323,  129,  305,  214,
      317,  317,  288,  304,  334,  303,  317,  317,  193,  302,
      190,  289,  333,  190,  333,  301,  300,  299,  298,  190,
      289,  188,  188,  188,  188,  244,  188,  188,  188,  188,
      188,  188,  188,  288,  188,  188,  188,  335,  335,  188,
      188,  188,  188,  188,  188,  335,  335,  335,  335,  188,
      190,  289,  335,  335,  335,  335,  335,  335,  335,  335,

      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  188,  188,  188,  244,  297,
      296,  214,  214,  290,  295,  336,  294,  323,  323,  293,
      292,  214,  287,  286,  239,  285,  237,  284,  282,  280,
      193,  291,  191,  191,  191,  191,  191,  191,  191,  244,
      191,  191,  191,  191,  290,  191,  191,  191,  337,  337,
      191,  191,  191,  191,  191,  191,  337,  337,  337,  337,
      191,  193,  291,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  191,  191,  191,  249,

      244,  332,  246,  341,  249,  244,  342,  246,  249,  279,
      278,  246,  344,  344,  345,  345,  348,  249,  249,  214,
      246,  246,  277,  276,  333,  190,  348,  193,  343,  333,
      332,  244,  341,  333,  349,  342,  290,  244,  275,  274,
      345,  345,  333,  333,  349,  288,  273,  272,  271,  344,
      344,  270,  269,  193,  291,  268,  267,  343,  266,  129,
      214,  265,  190,  289,  332,  332,  332,  350,  351,  332,
      332,  352,  332,  332,  332,  332,  332,  353,  332,  332,
      354,  354,  332,  332,  332,  332,  332,  332,  355,  355,
      355,  355,  332,  333,  332,  355,  355,  355,  355,  355,

      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  332,  332,
      332,  249,  264,  249,  246,  249,  246,  263,  246,  348,
      262,  348,  249,  261,  214,  246,  260,  354,  354,  259,
      348,  258,  356,  257,  354,  354,  333,  349,  333,  349,
      333,  256,  255,  214,  243,  129,  242,  333,  349,  332,
      332,  332,  332,  249,  332,  332,  246,  332,  332,  332,
      332,  348,  332,  332,  332,  357,  357,  332,  332,  332,
      332,  332,  332,  357,  357,  357,  357,  332,  333,  349,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,

      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  332,  332,  332,  249,  241,  249,  246,
      240,  246,  239,  237,  235,  234,  348,  233,  358,  358,
      358,  358,  232,  231,  230,  229,  228,  227,  226,  223,
      222,  333,  214,  333,  349,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   89,  220,   89,   89,   89,

       89,   89,   89,   89,   89,  100,  219,  100,  100,  100,
      100,  100,  100,  100,  100,  101,  101,  109,  109,  218,
      109,  109,  109,  144,  214,  215,  144,  144,  144,  144,
      144,  214,  144,  152,  213,  152,  212,  152,  152,  152,
      152,  211,  152,  160,  210,  209,  208,  160,  160,  160,
      160,  204,  160,  168,  203,  202,  168,  168,  168,  168,
      177,  201,  177,  177,  177,  177,  177,  177,  177,  177,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      197,  200,  197,  197,  236,  236,  236,  236,  236,  236,

      236,  199,  236,  238,  238,  238,  238,  238,  238,  238,
      198,  238,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  281,  281,  281,  281,  281,  281,  281,  187,
      281,  283,  283,  283,  283,  283,  283,  283,  186,  283,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      185,  182,  181,  180,  179,  178,  176,  169,  161,  143,
      140,  139,  134,  133,  132,  125,  118,  110,  104,  103,
      102,   99,   96,   95,   90,   88,  359,   83,   83,   82,

       82,   81,   81,   80,   80,   19,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359
    } ;

static const flex_int16_t yy_chk[1164] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    3,
        4,    5,    6,    7,  347,    7,    5,    6,    7,    8,
       27,    8,   29,   27,    8,   29,    9,   10,    9,   10,
       30,   30,   45,   49,    3,    4,   45,  346,    5,    6,
        7,    9,   10,   49,  339,   22,    8,   22,   22,   22,

       46,   22,   46,    9,   10,   32,  338,   32,   32,   53,
       42,   47,   35,   42,   35,   35,   58,   53,   35,   42,
       58,   47,   42,   42,   47,   66,   57,   66,    9,   10,
        9,   10,   35,   50,   70,   50,   52,  105,   50,   70,
       50,   57,   52,   52,   61,   61,   84,   52,   84,   75,
       93,  214,   93,   93,  214,   79,   66,   94,   94,   95,
       66,   95,  105,  106,  128,   70,  184,   66,  184,   70,
       66,   97,   66,   97,   97,  109,   70,   97,  330,   70,
       75,   70,  107,  107,   75,  106,   79,  118,  183,  183,
       79,   75,  118,  109,   75,  188,   75,   79,  119,  108,

       79,  108,   79,  108,  108,  137,  119,  128,  133,  137,
      128,  189,  190,  133,  190,  197,  191,  108,  192,  189,
      188,  193,  245,  192,  195,  195,  193,  244,  246,  329,
      194,  194,  328,  197,  194,  248,  246,  189,  191,  190,
      194,  192,  252,  194,  194,  244,  327,  245,  193,  247,
      249,  247,  326,  246,  246,  249,  250,  248,  253,  291,
      325,  250,  311,  310,  251,  251,  254,  252,  251,  309,
      254,  254,  249,  249,  251,  308,  247,  251,  251,  307,
      253,  291,  304,  250,  254,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,

      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  289,  321,  302,  300,  299,  297,  321,  296,
      295,  294,  293,  292,  287,  286,  285,  284,  283,  282,
      281,  280,  279,  278,  277,  321,  321,  289,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,

      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  314,  322,  315,  316,  320,
      315,  276,  320,  314,  317,  322,  322,  275,  274,  273,
      316,  316,  317,  272,  317,  271,  317,  317,  322,  269,
      314,  314,  315,  316,  320,  268,  267,  266,  265,  317,
      317,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,

      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  323,  264,
      263,  262,  261,  323,  260,  323,  259,  323,  323,  257,
      255,  243,  242,  239,  238,  237,  236,  235,  234,  231,
      323,  323,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  332,

      334,  333,  332,  333,  340,  336,  333,  340,  341,  230,
      229,  341,  334,  334,  336,  336,  341,  349,  342,  228,
      349,  342,  226,  225,  332,  334,  342,  336,  333,  340,
      343,  345,  343,  341,  341,  343,  345,  344,  224,  223,
      345,  345,  349,  342,  342,  344,  222,  221,  220,  344,
      344,  219,  218,  345,  345,  216,  215,  343,  213,  212,
      211,  210,  344,  344,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,

      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  351,  209,  352,  351,  353,  352,  208,  353,  351,
      207,  352,  354,  206,  205,  354,  204,  353,  353,  203,
      354,  202,  354,  201,  354,  354,  351,  351,  352,  352,
      353,  200,  199,  198,  187,  186,  185,  354,  354,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,

      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  356,  182,  358,  356,
      181,  358,  180,  179,  178,  176,  358,  169,  356,  356,
      358,  358,  161,  143,  142,  141,  140,  139,  138,  136,
      135,  356,  134,  358,  358,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  365,  132,  365,  365,  365,

      365,  365,  365,  365,  365,  366,  131,  366,  366,  366,
      366,  366,  366,  366,  366,  367,  367,  368,  368,  130,
      368,  368,  368,  369,  129,  127,  369,  369,  369,  369,
      369,  126,  369,  370,  125,  370,  124,  370,  370,  370,
      370,  123,  370,  371,  122,  121,  120,  371,  371,  371,
      371,  117,  371,  372,  116,  115,  372,  372,  372,  372,
      373,  114,  373,  373,  373,  373,  373,  373,  373,  373,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      376,  113,  376,  376,  377,  377,  377,  377,  377,  377,

      377,  112,  377,  378,  378,  378,  378,  378,  378,  378,
      111,  378,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  381,  381,  381,  381,  381,  381,  381,  104,
      381,  382,  382,  382,  382,  382,  382,  382,  103,  382,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      102,   92,   91,   90,   88,   87,   85,   78,   74,   62,
       60,   59,   56,   55,   54,   51,   48,   43,   41,   40,
       39,   36,   34,   33,   26,   23,   19,   18,   17,   16,

       15,   14,   13,   12,   11,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[103] =
    {   0,
1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 
    0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 2 "scanner.l"
    #include <stdio.h>
    #include <ctype.h>
    #include <stdlib.h>
    #include <string.h>
    #include "parser.tab.h"

    #pragma warning (disable: 4005)
    #include "parser.hpp"
    #include "astNodes.hpp"
    using namespace std;

    #define Stack_SIZE 100
    void push();
    void pop();
    void show();

    int top = -1;
    int stack_arr[Stack_SIZE];

    void push(int insert_item)
    {
        if (top == Stack_SIZE - 1)
            printf("\nOverflow!!");

        else
        {
            top++;
            stack_arr[top] = insert_item;
        }
    }

    void pop()
    {
        if (top == -1)
            printf("\nUnderflow!!");

        else
            top--;
    }

    void stackshow()
    {
        if (top == -1)
            printf("\nUnderflow!!");

        else
        {
            printf("\nElements present in the stack: \n");
            for (int i = top; i >= 0; --i)
                printf("%d\n", stack_arr[i]);
        }
    } 

    #define keyword_size 10
    char keyword[keyword_size];

    #define MAX_STR_CONST 256
    char string_buf[MAX_STR_CONST];
    char *string_buf_ptr;

    int current_indentation = 0;
    int spaces = 0;

    extern YYSTYPE yylval;
#line 989 "scanner.cpp"

#line 991 "scanner.cpp"

#define INITIAL 0
#define DOUBLE_STRING 1
#define SINGLE_STRING 2
#define COMMENT_STRING 3
#define COMMENT_STRING_DOUBLE 4
#define INDENTSTATE 5
#define DEDENTALLSTATE 6
#define DEDENTSTATE 7
#define NEWNEW 8

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 118 "scanner.l"


#line 1219 "scanner.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 360 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1106 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 120 "scanner.l"
{
                            BEGIN(INDENTSTATE);
                            if(top < 0)
                                push(0);

                            spaces = 0;
                            for(int i = 0; i < yyleng; i++){
                                if (yytext[i] == ' ') {
                                    spaces++;
                                } else if (yytext[i] == '\t') {
                                    spaces += 8;
                                }
                            }
                            push(spaces);

                            current_indentation = spaces;
                            unput(' ');

                            return NEWLINE;
                        }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 141 "scanner.l"
{
                            if(top < 0)
                                push(0);

                            spaces = 0;
                            for(int i = 0; i < yyleng; i++){
                                if (yytext[i] == ' ') {
                                    spaces++;
                                } else if (yytext[i] == '\t') {
                                    spaces += 8;
                                }
                            }
                            current_indentation = spaces;

                            unput(' ');
                            BEGIN(DEDENTSTATE);
                            return NEWLINE;
                        }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 160 "scanner.l"
{ 
                            BEGIN(DEDENTALLSTATE);
                            unput(' ');
                            return NEWLINE;
                        }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 166 "scanner.l"
{}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(DOUBLE_STRING):
case YY_STATE_EOF(SINGLE_STRING):
case YY_STATE_EOF(COMMENT_STRING):
case YY_STATE_EOF(COMMENT_STRING_DOUBLE):
case YY_STATE_EOF(INDENTSTATE):
case YY_STATE_EOF(DEDENTALLSTATE):
case YY_STATE_EOF(DEDENTSTATE):
case YY_STATE_EOF(NEWNEW):
#line 168 "scanner.l"
{
                    BEGIN(NEWNEW);
                    unput(' ');

                    if(stack_arr[top] == 0)
                        return 0;
                }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 177 "scanner.l"
{}
	YY_BREAK
case 6:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 179 "scanner.l"
{}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 181 "scanner.l"
{}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 183 "scanner.l"
{yylval.strval = strdup(yytext); return yytext[0];}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 185 "scanner.l"
{return ARRAY;}
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 187 "scanner.l"
{}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 189 "scanner.l"
{yylval.strval = strdup(yytext); return yytext[0];}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 191 "scanner.l"
{yylval.strval = strdup(yytext); return yytext[0];}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 193 "scanner.l"
{yylval.strval = strdup(yytext); return yytext[0];} 
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 195 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return DEF;
                        }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 200 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return IF;
                        }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 205 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return ELIF;
                        }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 210 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return ELSE;
                        }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 215 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return BREAK;
                        }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 220 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return CONTINUE;
                        }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 225 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return GLOBAL;
                        }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 230 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return NONLOCAL;
                        }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 235 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return YIELD;
                        }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 240 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return RETURN;
                        }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 245 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return LT;
                        }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 250 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return GT;
                        }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 255 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return LTE;
                        }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 260 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return GTE;
                        }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 265 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return EQUAL;
                        }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 270 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return WHILE;
                        }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 275 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return FOR;
                        }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 280 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return IN;
                        }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 285 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return RANGE;
                        }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 290 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return PRINT;
                        }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 295 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return INPUT;
                        }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 300 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return CLASS;
                        }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 305 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return TRY;
                        }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 310 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return EXCEPT;
                        }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 315 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return MATCH;
                        }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 320 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return CASE;
                        }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 325 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return WITH;
                        }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 330 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return AS;
                        }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 335 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return INT;
                        }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 340 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return FLOAT;
                        }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 345 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return STR;
                        }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 350 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return BOOL;
                        }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 355 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return LIST;
                        }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 360 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return PASS;
                        }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 365 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return OR;
                        }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 370 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return AND;
                        }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 375 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return TRUE_TOK;
                        }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 380 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return FALSE_TOK;
                        }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 386 "scanner.l"
{
                            yylval.astNode = new IdentifierNode("IDENTIFIER", "Identifier", yytext);
                            return ID;
                        }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 391 "scanner.l"
{
                            yylval.astNode = new NumberNode("INT", "int", atoi(yytext));
                            return INT_NUMBER;
                        }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 396 "scanner.l"
{
                            yylval.astNode = new NumberNode("FLOAT", "float", atoi(yytext));
                            return FLOAT_NUMBER;
                        }
	YY_BREAK

case 55:
YY_RULE_SETUP
#line 403 "scanner.l"
{
        BEGIN(INITIAL);
        return INDENT;
    }
	YY_BREAK


case 56:
YY_RULE_SETUP
#line 410 "scanner.l"
{

        int flag = 1;
        for (int i = 0; i <= top; i++) {
            if (current_indentation == stack_arr[i])
                flag = 0;
        }

        if(flag)
            return INDENTERROR;

        int end = 1;
        while(current_indentation < stack_arr[top])
        {
            unput(' ');
            BEGIN(DEDENTSTATE);
            end = 0;
            pop();

            return DEDENT;
        }

        if(end)
            BEGIN(INITIAL);

    }
	YY_BREAK


case 57:
YY_RULE_SETUP
#line 439 "scanner.l"
{
        if (top < 0)
            push(0);

        if (stack_arr[top] > 0) {
            while (top > 0) {
                unput(' ');
                BEGIN(DEDENTALLSTATE);
                pop();

                return DEDENT;
            }
        } else {
            BEGIN(INITIAL);
        }
    }
	YY_BREAK


case 58:
YY_RULE_SETUP
#line 458 "scanner.l"
{
        BEGIN(DEDENTALLSTATE);
        unput(' ');
        return NEWLINE;
    }
	YY_BREAK

case 59:
YY_RULE_SETUP
#line 466 "scanner.l"
{ string_buf_ptr = string_buf; BEGIN(DOUBLE_STRING); }    
	YY_BREAK

case 60:
YY_RULE_SETUP
#line 469 "scanner.l"
{*string_buf_ptr = '\0'; BEGIN(INITIAL); yylval.astNode = new StringNode("STRING", "string", string_buf); return STRING;} 
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 470 "scanner.l"
{              }
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 471 "scanner.l"
{printf("error in line %d\n", yylineno); BEGIN(INITIAL);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 472 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 473 "scanner.l"
{*string_buf_ptr++ = '\t';}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 474 "scanner.l"
{*string_buf_ptr++ = '\r';}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 475 "scanner.l"
{*string_buf_ptr++ = '\b';}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 476 "scanner.l"
{*string_buf_ptr++ = '\f';}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 477 "scanner.l"
{*string_buf_ptr++ = '\"';} 
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 478 "scanner.l"
{
        char *yptr = yytext;
        while ( *yptr )
            *string_buf_ptr++ = *yptr++;        
    }
	YY_BREAK

case 70:
YY_RULE_SETUP
#line 485 "scanner.l"
{ string_buf_ptr = string_buf; BEGIN(SINGLE_STRING); }    
	YY_BREAK

case 71:
YY_RULE_SETUP
#line 487 "scanner.l"
{*string_buf_ptr = '\0'; BEGIN(INITIAL); yylval.astNode = new StringNode("STRING", "string", string_buf); return STRING;}
	YY_BREAK
case 72:
/* rule 72 can match eol */
YY_RULE_SETUP
#line 488 "scanner.l"
{              }
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 489 "scanner.l"
{printf("line%d, ERROR: new line in string\n", yylineno); BEGIN(INITIAL);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 490 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 491 "scanner.l"
{*string_buf_ptr++ = '\t';}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 492 "scanner.l"
{*string_buf_ptr++ = '\r';}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 493 "scanner.l"
{*string_buf_ptr++ = '\b';}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 494 "scanner.l"
{*string_buf_ptr++ = '\f';}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 495 "scanner.l"
{*string_buf_ptr++ = '\'';} 
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 496 "scanner.l"
{
        char *yptr = yytext;
        while ( *yptr )
            *string_buf_ptr++ = *yptr++;        
    }
	YY_BREAK

case 81:
YY_RULE_SETUP
#line 503 "scanner.l"
{   
                            int i = 0;
                            strcpy(keyword, " ");

                            while(yytext[i] != ' ') {
                                if (yytext[i] == '\'') 
                                    break;

                                keyword[i] = yytext[i];
                                i++;
                            }

                            string_buf_ptr = string_buf; BEGIN(COMMENT_STRING); 

                            if (strcmp(keyword, "=") == 0) {
                                return yytext[0];
                            }
                            else if (strcmp(keyword, "(") == 0 || strcmp(keyword, "{") == 0 || strcmp(keyword, "[") == 0) {
                                return yytext[0];
                            }

                            else {
                                if ( strcmp(keyword, "return") == 0) {
                                    return RETURN;
                                }
                            }

                            
                        }
	YY_BREAK

case 82:
YY_RULE_SETUP
#line 534 "scanner.l"
{*string_buf_ptr = '\0'; BEGIN(INITIAL); yylval.astNode = new StringNode("STRING", "string", string_buf); return STRING;}
	YY_BREAK
case 83:
/* rule 83 can match eol */
YY_RULE_SETUP
#line 535 "scanner.l"
{}
	YY_BREAK
case 84:
/* rule 84 can match eol */
YY_RULE_SETUP
#line 536 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 537 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 538 "scanner.l"
{*string_buf_ptr++ = '\t';}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 539 "scanner.l"
{*string_buf_ptr++ = '\r';}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 540 "scanner.l"
{*string_buf_ptr++ = '\b';}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 541 "scanner.l"
{*string_buf_ptr++ = '\f';}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 542 "scanner.l"
{
        char *yptr = yytext;
        while ( *yptr )
            *string_buf_ptr++ = *yptr++;        
    }
	YY_BREAK

case 91:
YY_RULE_SETUP
#line 549 "scanner.l"
{   
                            int i = 0;
                            strcpy(keyword, " ");

                            while(yytext[i] != ' ') {
                                if (yytext[i] == '\"') 
                                    break;

                                keyword[i] = yytext[i];
                                i++;
                            }

                            string_buf_ptr = string_buf; BEGIN(COMMENT_STRING_DOUBLE); 

                            if (strcmp(keyword, "=") == 0) {
                                return yytext[0];
                            }

                            else if (strcmp(keyword, "(") == 0 || strcmp(keyword, "{") == 0 || strcmp(keyword, "[") == 0) {
                                return yytext[0];
                            }

                            else {
                                if ( strcmp(keyword, "return") == 0) {
                                    return RETURN;
                                }
                            }
                            
                        }
	YY_BREAK

case 92:
YY_RULE_SETUP
#line 580 "scanner.l"
{*string_buf_ptr = '\0'; BEGIN(INITIAL); yylval.astNode = new StringNode("STRING", "string", string_buf); return STRING;}
	YY_BREAK
case 93:
/* rule 93 can match eol */
YY_RULE_SETUP
#line 581 "scanner.l"
{}
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 582 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 583 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 584 "scanner.l"
{*string_buf_ptr++ = '\t';}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 585 "scanner.l"
{*string_buf_ptr++ = '\r';}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 586 "scanner.l"
{*string_buf_ptr++ = '\b';}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 587 "scanner.l"
{*string_buf_ptr++ = '\f';}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 588 "scanner.l"
{
        char *yptr = yytext;
        while ( *yptr )
            *string_buf_ptr++ = *yptr++;        
    }
	YY_BREAK

case 101:
YY_RULE_SETUP
#line 595 "scanner.l"
{printf("error in %d is %s",yylineno,yytext);}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 597 "scanner.l"
ECHO;
	YY_BREAK
#line 2129 "scanner.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,(yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,(yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 360 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 360 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 359);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc((yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 597 "scanner.l"

