#line 1 "scanner.cpp"

#line 3 "scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 3
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    #define yy_create_buffer yy_create_buffer

    #define yy_delete_buffer yy_delete_buffer

    #define yy_scan_buffer yy_scan_buffer

    #define yy_scan_string yy_scan_string

    #define yy_scan_bytes yy_scan_bytes

    #define yy_init_buffer yy_init_buffer

    #define yy_flush_buffer yy_flush_buffer

    #define yy_load_buffer_state yy_load_buffer_state

    #define yy_switch_to_buffer yy_switch_to_buffer

    #define yypush_buffer_state yypush_buffer_state

    #define yypop_buffer_state yypop_buffer_state

    #define yyensure_buffer_stack yyensure_buffer_stack

    #define yylex yylex

    #define yyrestart yyrestart

    #define yylex_init yylex_init

    #define yylex_init_extra yylex_init_extra

    #define yylex_destroy yylex_destroy

    #define yyget_debug yyget_debug

    #define yyset_debug yyset_debug

    #define yyget_extra yyget_extra

    #define yyset_extra yyset_extra

    #define yyget_in yyget_in

    #define yyset_in yyset_in

    #define yyget_out yyget_out

    #define yyset_out yyset_out

    #define yyget_leng yyget_leng

    #define yyget_text yyget_text

    #define yyget_lineno yyget_lineno

    #define yyset_lineno yyset_lineno

    #define yywrap yywrap

    #define yyalloc yyalloc

    #define yyrealloc yyrealloc

    #define yyfree yyfree

    #define yytext yytext

    #define yyleng yyleng

    #define yyin yyin

    #define yyout yyout

    #define yy_flex_debug yy_flex_debug

    #define yylineno yylineno

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 96
#define YY_END_OF_BUFFER 97
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[351] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   97,   95,    5,    3,
       53,    9,   64,   12,   12,   11,    7,   11,    7,   48,
        7,   23,   10,   24,   47,   47,   47,   47,   12,   95,
       11,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   63,
       56,   54,   96,   74,   67,   65,   96,   84,   78,   96,
       96,   96,   94,   88,   96,   96,   50,   52,   51,    2,
        0,    4,    0,    0,    9,    0,    0,    0,   48,    0,
        0,   25,    0,   27,   26,   47,   47,   47,   47,    0,

        0,    0,    0,    0,    6,   47,   40,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       14,   47,   30,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   63,   55,   62,
       60,   61,   57,   59,   58,   74,   66,   73,   71,   72,
       68,   70,   69,   84,    0,   77,   82,   83,   79,   81,
       80,   94,    0,   87,   92,   93,   89,   91,   90,    0,
        4,    0,    0,    0,    0,    0,   49,    1,   47,   47,
       47,    0,    0,    0,    0,    0,    0,    0,    0,    8,
        0,   47,   47,   47,   47,   47,   47,   13,   47,   47,

       47,   47,   47,   29,   47,   47,    0,   47,   47,   41,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   43,
       35,   47,   47,   47,   76,   86,    0,    0,    0,    0,
        0,    0,   85,   75,   47,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   47,   44,   47,   38,
       47,   47,   15,   16,   47,   47,   47,   47,   47,   47,
       47,   45,   47,   47,   46,   47,   47,   47,   47,   47,
       39,   47,    0,    0,    0,    0,    0,    0,    0,    8,
        0,    8,   47,   17,   34,   47,   47,   47,   42,   47,
       47,   33,   47,   37,   47,   32,   31,   47,   28,   21,

        0,    0,    9,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   47,   36,   47,   19,   47,
       22,    4,    0,    0,    0,    0,    0,    0,   47,   47,
        0,    0,    0,    0,    0,    0,   18,   20,    0,    8,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    1,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       17,   16,   16,   16,   16,   16,   16,   18,   19,   20,
       21,   22,    1,    1,   23,   23,   23,   23,   23,   24,
       23,   23,   23,   23,   23,   23,   23,   25,   23,   23,
       23,   23,   23,   26,   23,   23,   23,   23,   23,   23,
       27,   28,   29,    1,   30,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   23,   40,   41,   42,   43,
       44,   45,   23,   46,   47,   48,   49,   23,   50,   51,
       52,   23,   53,    1,   54,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[55] =
    {   0,
        1,    1,    2,    1,    3,    1,    4,    1,    1,    1,
        1,    5,    6,    1,    1,    7,    8,    1,    1,    1,
        1,    1,    7,    7,    7,    7,    1,    9,    5,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,   10,   10
    } ;

static const flex_int16_t yy_base[375] =
    {   0,
        0,    0,   52,   53,   56,   57,   62,   63,   69,   72,
     1065, 1064, 1063, 1062, 1061, 1060, 1063, 1070, 1070,   97,
     1057,    0, 1054,   66, 1070, 1070,   71,   45, 1070,   78,
     1057, 1038,  103, 1037,    0, 1026, 1012, 1009,  104, 1051,
        0,   36,   52,   75, 1018,   77,   88, 1011,   94,  100,
     1020, 1006, 1003,  102,  107, 1000, 1001,   49, 1007,    0,
     1070, 1070,  140,    0, 1070, 1070,  146,    0, 1070, 1070,
     1038,  155,    0, 1070, 1039,  161, 1070, 1070, 1070,  110,
     1038,    0, 1035, 1036,    0, 1033, 1034, 1031,  130,  134,
      111, 1070,  150, 1070, 1070,    0,  996,  993,  965,  135,

      128,  143,  194,  150, 1070,  971,  929,  923,  922,  880,
      890,  877,  125,  126,  884,  869,  867,  864,  863,  858,
      896,  852,  167,  887,  848,  838,  824,  126,  771,  778,
      138,  768,  769,  762,  774,  764,  776,    0, 1070, 1070,
     1070, 1070, 1070, 1070, 1070,    0, 1070, 1070, 1070, 1070,
     1070, 1070, 1070,    0,  803, 1070, 1070, 1070, 1070, 1070,
     1070,    0,  804, 1070, 1070, 1070, 1070, 1070, 1070,  801,
        0,  798,  799,  795,  796,  793,  151,  198,  752,  762,
      704,  185,  209,  213,  168,  210,  177,  220,  203, 1070,
      214,  703,  696,  705,  700,  687,  685,  728,  695,  695,

      692,  694,  692,  718,  678,  682,  223,  667,  659,    0,
      673,  656,  670,  661,  654,  650,  643,  595,  582,    0,
      626,  588,  590,  586, 1070, 1070,  621,  618,  619,  618,
      613,  606, 1070, 1070,  576,  217,  226,  230,  229,  233,
      237,  244,  263,  243,  245,  265,  564,    0,  569,    0,
      561,  562,  596,  586,  544,  538,  527,  484,  466,  463,
      475,    0,  470,  463,  502,  455,  466,  462,  450,  459,
      428,  394,  420,  419,  416,  413,  413,  406,  294,  250,
      348,  246,  364,  407,  403,  250,  244,  250,    0,  249,
      241,    0,  257,    0,  254,    0,    0,  241,  279,  271,

      259,  256, 1070,    0,  257,  398,  399,  405,  434,    0,
      401,  402,  482,  488,  517,  211,  252,  198,  241,  168,
      191, 1070,  485,  569,  568,    0,  570,    0,  150,  129,
      486,  576,  587,  575,  590,  605,   89,   78,  634,  586,
        0,  684,  687,  690,  712,  741,  693,    0,  791, 1070,
      820,  830,  840,  850,  860,  870,  874,  880,  888,  898,
      908,  918,  925,  935,  945,  951,  959,  968,  977,  987,
      997, 1006, 1015, 1025
    } ;

static const flex_int16_t yy_def[375] =
    {   0,
      350,    1,  351,  351,  352,  352,  353,  353,  354,  354,
      355,  355,  355,  355,  355,  355,  350,  350,  350,  350,
      350,  356,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  357,  357,  357,  357,  358,  350,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  359,
      350,  350,  350,  360,  350,  350,  350,  361,  350,  350,
      350,  350,  362,  350,  350,  350,  350,  350,  350,  350,
      350,  363,  350,  350,  356,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  357,  357,  357,  357,  364,

      365,  350,  350,  366,  350,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  359,  350,  350,
      350,  350,  350,  350,  350,  360,  350,  350,  350,  350,
      350,  350,  350,  361,  350,  350,  350,  350,  350,  350,
      350,  362,  350,  350,  350,  350,  350,  350,  350,  350,
      363,  350,  367,  368,  350,  350,  350,  350,  357,  357,
      357,  364,  350,  369,  365,  350,  370,  358,  350,  350,
      366,  357,  357,  357,  357,  357,  357,  357,  357,  357,

      357,  357,  357,  357,  357,  357,  350,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  350,  350,  371,  372,  367,  350,
      368,  350,  350,  350,  357,  350,  364,  364,  369,  365,
      365,  370,  358,  364,  365,  350,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  371,  350,  372,  350,  350,  350,  350,  364,
      350,  365,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,

      350,  350,  350,  279,  364,  373,  364,  364,  350,  281,
      373,  365,  365,  365,  350,  357,  357,  357,  357,  357,
      357,  350,  373,  374,  364,  309,  365,  315,  357,  357,
      373,  373,  373,  374,  364,  365,  357,  357,  350,  373,
      339,  373,  373,  373,  373,  350,  373,  346,  373,    0,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350
    } ;

static const flex_int16_t yy_nxt[1125] =
    {   0,
       18,   19,   20,   19,   21,   22,   23,   24,   25,   26,
       26,   27,   28,   29,   26,   30,   30,   31,   29,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   25,   41,
       42,   43,   44,   45,   46,   47,   48,   35,   49,   35,
       50,   51,   52,   53,   54,   55,   56,   57,   35,   58,
       35,   59,   24,   25,   61,   61,   62,   62,   65,   65,
       89,   89,   66,   66,   69,   69,   70,   70,   71,   71,
       87,   74,   88,   75,   74,   87,   75,   88,  106,   63,
       63,  207,  107,   67,   67,   70,  135,  136,   70,   72,
       72,   90,  207,   89,   89,  108,   76,  109,   80,   76,

       80,   81,   82,   83,   93,  110,   93,   87,  100,   88,
      101,   80,  178,   80,  178,  111,  102,  114,  112,  103,
      103,   70,   70,   94,   70,   70,  116,  115,  117,  121,
      125,  118,  129,  119,  186,  122,  123,  131,  126,  183,
      124,  132,  139,   90,  140,   89,   89,  130,  147,  177,
      177,   93,  148,   93,   87,  187,   88,  156,  103,  103,
      198,  188,  184,  164,  199,  124,  177,  177,  214,  338,
      207,  141,  200,  124,  236,  142,  217,  149,  190,  185,
      218,  150,  143,  241,  337,  144,  157,  145,  151,  236,
      158,  152,  165,  153,  207,  187,  166,  159,  330,  178,

      160,  178,  161,  167,  242,  188,  168,  189,  169,  103,
      103,  209,  184,  233,  210,  182,  234,  238,  246,  246,
      188,  188,  190,  243,  244,  188,  245,   87,  188,   88,
      236,  182,  102,  238,  236,  103,  103,  190,  190,  236,
      239,  279,  190,  236,  207,  190,  185,  236,  281,  124,
      241,  236,  236,  184,  236,  207,  239,  184,  280,  329,
      187,  236,  322,  322,  187,  282,  243,  244,  279,  245,
      184,  242,  187,  187,  207,  102,  188,  184,  103,  103,
      246,  246,  207,  321,  184,  280,  320,  124,  124,  319,
      318,  317,  316,  190,  182,  182,  182,  304,  305,  182,

      306,  182,  182,  182,  182,  182,  307,  182,  182,  308,
      308,  182,  182,  182,  182,  182,  309,  309,  309,  309,
      182,  184,  182,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  182,  182,  185,  185,
      185,  310,  311,  185,  312,  185,  185,  185,  185,  185,
      313,  185,  185,  314,  314,  185,  185,  185,  185,  185,
      315,  315,  315,  315,  185,  187,  185,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,

      185,  185,  241,  236,  238,  241,  207,  238,  236,  236,
      207,  124,  303,  281,  308,  308,  279,  303,  325,  302,
      308,  308,  276,  301,  274,  324,  184,  300,  324,  187,
      282,  207,  184,  280,  182,  182,  182,  182,  236,  182,
      182,  182,  182,  182,  182,  279,  182,  182,  182,  326,
      326,  182,  182,  182,  182,  182,  326,  326,  326,  326,
      182,  184,  280,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  182,  182,  236,  241,
      241,  238,  238,  299,  236,  298,  297,  314,  314,  281,

      124,  327,  296,  314,  314,  207,  295,  294,  293,  187,
      292,  291,  324,  324,  290,  187,  282,  185,  185,  185,
      185,  185,  185,  236,  185,  185,  185,  185,  281,  185,
      185,  185,  328,  328,  185,  185,  185,  185,  185,  328,
      328,  328,  328,  185,  187,  282,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  185,
      185,  323,  236,  332,  289,  333,  236,  323,  288,  332,
      241,  333,  238,  335,  335,  336,  336,  339,  287,  207,
      241,  241,  238,  238,  236,  184,  334,  187,  339,  207,

      286,  279,  334,  324,  340,  335,  335,  285,  284,  283,
      124,  236,  278,  324,  324,  340,  281,  184,  280,  232,
      336,  336,  277,  230,  276,  274,  272,  271,  270,  207,
      269,  268,  187,  282,  323,  323,  323,  341,  342,  323,
      343,  323,  323,  323,  323,  323,  344,  323,  323,  345,
      345,  323,  323,  323,  323,  323,  346,  346,  346,  346,
      323,  324,  323,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  323,  323,  241,  267,
      238,  241,  266,  238,  241,  339,  238,  241,  339,  238,

      265,  264,  263,  262,  261,  345,  345,  260,  349,  349,
      259,  324,  340,  258,  324,  340,  241,  324,  238,  124,
      324,  207,  257,  339,  256,  347,  255,  345,  345,  254,
      253,  207,  252,  251,  250,  249,  248,  247,  124,  324,
      340,  323,  323,  323,  323,  241,  323,  238,  323,  323,
      323,  323,  339,  323,  323,  323,  348,  348,  323,  323,
      323,  323,  323,  348,  348,  348,  348,  323,  324,  340,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  323,  323,  241,  124,  238,  235,  234,

      233,  232,  339,  230,  228,  227,  349,  349,  226,  225,
      224,  223,  222,  221,  220,  219,  216,  215,  324,  340,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       85,  213,   85,   85,   85,   85,   85,   85,   85,   85,
       96,   96,  104,  104,  212,  104,  104,  104,  138,  211,
      207,  138,  138,  138,  138,  138,  208,  138,  146,  207,

      146,  206,  146,  146,  146,  146,  205,  146,  154,  204,
      203,  202,  154,  154,  154,  154,  201,  154,  162,  197,
      196,  162,  162,  162,  162,  171,  195,  171,  171,  171,
      171,  171,  171,  171,  171,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  191,  194,  191,  191,  229,
      229,  229,  229,  229,  229,  229,  193,  229,  231,  231,
      231,  231,  231,  231,  231,  192,  231,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  273,  273,  273,

      273,  273,  273,  273,  124,  273,  275,  275,  275,  275,
      275,  275,  275,  181,  275,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  180,  179,  176,  175,  174,
      173,  172,  170,  163,  155,  137,  134,  133,  124,  128,
      127,  120,  113,  105,   99,   98,   97,   95,   92,   91,
       86,   84,  350,   79,   79,   78,   78,   77,   77,   17,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,

      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350
    } ;

static const flex_int16_t yy_chk[1125] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    3,    4,    5,    6,
       28,   28,    5,    6,    7,    8,    7,    8,    7,    8,
       24,    9,   24,    9,   10,   27,   10,   27,   42,    3,
        4,  338,   42,    5,    6,    9,   58,   58,   10,    7,
        8,   30,  337,   30,   30,   43,    9,   43,   20,   10,

       20,   20,   20,   20,   33,   44,   33,   33,   39,   33,
       39,   80,   91,   80,   91,   44,   39,   46,   44,   39,
       39,    9,    9,   33,   10,   10,   47,   46,   47,   49,
       50,   47,   54,   47,  101,   49,   49,   55,   50,  100,
       49,   55,   63,   89,   63,   89,   89,   54,   67,   90,
       90,   93,   67,   93,   93,  101,   93,   72,  102,  102,
      113,  104,  100,   76,  114,  113,  177,  177,  128,  330,
      123,   63,  114,  128,  185,   63,  131,   67,  104,  187,
      131,   67,   63,  187,  329,   63,   72,   63,   67,  182,
       72,   67,   76,   67,  321,  185,   76,   72,  320,  178,

       72,  178,   72,   76,  187,  103,   76,  103,   76,  103,
      103,  123,  182,  183,  123,  184,  186,  184,  189,  189,
      183,  186,  103,  188,  188,  191,  188,  207,  236,  207,
      237,  239,  188,  239,  238,  188,  188,  183,  186,  240,
      184,  238,  191,  241,  319,  236,  242,  244,  241,  318,
      242,  245,  282,  237,  280,  317,  239,  238,  238,  316,
      240,  305,  302,  301,  241,  241,  243,  243,  305,  243,
      244,  242,  245,  282,  300,  243,  246,  280,  243,  243,
      246,  246,  299,  298,  305,  305,  295,  293,  291,  290,
      288,  287,  286,  246,  279,  279,  279,  279,  279,  279,

      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,

      281,  281,  306,  307,  306,  311,  285,  311,  312,  308,
      284,  283,  278,  312,  307,  307,  308,  277,  308,  276,
      308,  308,  275,  274,  273,  306,  307,  272,  311,  312,
      312,  271,  308,  308,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  313,  323,
      331,  323,  331,  270,  314,  269,  268,  313,  313,  314,

      267,  314,  266,  314,  314,  265,  264,  263,  261,  313,
      260,  259,  323,  331,  258,  314,  314,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  324,  325,  324,  257,  324,  327,  334,  256,  334,
      332,  334,  332,  325,  325,  327,  327,  332,  255,  254,
      340,  333,  340,  333,  335,  325,  324,  327,  333,  253,

      252,  335,  334,  332,  332,  335,  335,  251,  249,  247,
      235,  336,  232,  340,  333,  333,  336,  335,  335,  231,
      336,  336,  230,  229,  228,  227,  224,  223,  222,  221,
      219,  218,  336,  336,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  342,  217,
      342,  343,  216,  343,  344,  342,  344,  347,  343,  347,

      215,  214,  213,  212,  211,  344,  344,  209,  347,  347,
      208,  342,  342,  206,  343,  343,  345,  344,  345,  205,
      347,  204,  203,  345,  202,  345,  201,  345,  345,  200,
      199,  198,  197,  196,  195,  194,  193,  192,  181,  345,
      345,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  349,  180,  349,  179,  176,

      175,  174,  349,  173,  172,  170,  349,  349,  163,  155,
      137,  136,  135,  134,  133,  132,  130,  129,  349,  349,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      356,  127,  356,  356,  356,  356,  356,  356,  356,  356,
      357,  357,  358,  358,  126,  358,  358,  358,  359,  125,
      124,  359,  359,  359,  359,  359,  122,  359,  360,  121,

      360,  120,  360,  360,  360,  360,  119,  360,  361,  118,
      117,  116,  361,  361,  361,  361,  115,  361,  362,  112,
      111,  362,  362,  362,  362,  363,  110,  363,  363,  363,
      363,  363,  363,  363,  363,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  366,  109,  366,  366,  367,
      367,  367,  367,  367,  367,  367,  108,  367,  368,  368,
      368,  368,  368,  368,  368,  107,  368,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  371,  371,  371,

      371,  371,  371,  371,  106,  371,  372,  372,  372,  372,
      372,  372,  372,   99,  372,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,   98,   97,   88,   87,   86,
       84,   83,   81,   75,   71,   59,   57,   56,   53,   52,
       51,   48,   45,   40,   38,   37,   36,   34,   32,   31,
       23,   21,   17,   16,   15,   14,   13,   12,   11,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,

      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[97] =
    {   0,
1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 
    0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 2 "scanner.l"
    #include <stdio.h>
    #include <ctype.h>
    #include <stdlib.h>
    #include <string.h>
    #include "parser.tab.h"

    #define Stack_SIZE 100
    void push();
    void pop();
    void show();

    int top = -1;
    int stack_arr[Stack_SIZE];

    void push(int insert_item)
    {
        if (top == Stack_SIZE - 1)
            printf("\nOverflow!!");

        else
        {
            top++;
            stack_arr[top] = insert_item;
        }
    }

    void pop()
    {
        if (top == -1)
            printf("\nUnderflow!!");

        else
            top--;
    }

    void stackshow()
    {
        if (top == -1)
            printf("\nUnderflow!!");

        else
        {
            printf("\nElements present in the stack: \n");
            for (int i = top; i >= 0; --i)
                printf("%d\n", stack_arr[i]);
        }
    } 

    #define keyword_size 10
    char keyword[keyword_size];

    #define MAX_STR_CONST 256
    char string_buf[MAX_STR_CONST];
    char *string_buf_ptr;

    int current_indentation = 0;
    int spaces = 0;

    extern YYSTYPE yylval; 
#line 972 "scanner.cpp"

#line 974 "scanner.cpp"

#define INITIAL 0
#define DOUBLE_STRING 1
#define SINGLE_STRING 2
#define COMMENT_STRING 3
#define COMMENT_STRING_DOUBLE 4
#define INDENTSTATE 5
#define DEDENTALLSTATE 6
#define DEDENTSTATE 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 110 "scanner.l"


#line 1201 "scanner.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 351 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1070 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 112 "scanner.l"
{
                            BEGIN(INDENTSTATE);
                            if(top < 0)
                                push(0);

                            spaces = 0;
                            for(int i = 0; i < yyleng; i++){
                                if (yytext[i] == ' ') {
                                    spaces++;
                                } else if (yytext[i] == '\t') {
                                    spaces += 8;
                                }
                            }
                            push(spaces);

                            current_indentation = spaces;
                            unput(' ');

                            return NEWLINE;
                        }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 133 "scanner.l"
{
                            if(top < 0)
                                push(0);

                            spaces = 0;
                            for(int i = 0; i < yyleng; i++){
                                if (yytext[i] == ' ') {
                                    spaces++;
                                } else if (yytext[i] == '\t') {
                                    spaces += 8;
                                }
                            }
                            current_indentation = spaces;

                            unput(' ');
                            BEGIN(DEDENTSTATE);
                            return NEWLINE;
                        }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 152 "scanner.l"
{ 
                            BEGIN(DEDENTALLSTATE);
                            unput(' ');
                            return NEWLINE;
                        }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 158 "scanner.l"
{}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(DOUBLE_STRING):
case YY_STATE_EOF(SINGLE_STRING):
case YY_STATE_EOF(COMMENT_STRING):
case YY_STATE_EOF(COMMENT_STRING_DOUBLE):
case YY_STATE_EOF(INDENTSTATE):
case YY_STATE_EOF(DEDENTALLSTATE):
case YY_STATE_EOF(DEDENTSTATE):
#line 160 "scanner.l"
{
                    BEGIN(DEDENTALLSTATE);
                    unput(' ');

                    if(stack_arr[top] == 0)
                        return 0;
                }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 168 "scanner.l"
{}
	YY_BREAK
case 6:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 170 "scanner.l"
{}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 172 "scanner.l"
{yylval.strval = strdup(yytext); return yytext[0];}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 174 "scanner.l"
{return ARRAY;}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 176 "scanner.l"
{}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 178 "scanner.l"
{yylval.strval = strdup(yytext); return yytext[0];}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 180 "scanner.l"
{yylval.strval = strdup(yytext); return yytext[0];}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 182 "scanner.l"
{yylval.strval = strdup(yytext); return yytext[0];} 
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 184 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return DEF;
                        }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 189 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return IF;
                        }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 194 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return ELIF;
                        }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 199 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return ELSE;
                        }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 204 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return BREAK;
                        }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 209 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return CONTINUE;
                        }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 214 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return GLOBAL;
                        }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 219 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return NONLOCAL;
                        }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 224 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return YIELD;
                        }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 229 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return RETURN;
                        }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 234 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return LT;
                        }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 239 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return GT;
                        }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 244 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return LTE;
                        }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 249 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return GTE;
                        }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 254 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return EQUAL;
                        }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 259 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return WHILE;
                        }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 264 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return FOR;
                        }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 269 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return IN;
                        }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 274 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return RANGE;
                        }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 279 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return PRINT;
                        }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 284 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return INPUT;
                        }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 289 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return CLASS;
                        }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 294 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return TRY;
                        }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 299 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return EXCEPT;
                        }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 304 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return MATCH;
                        }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 309 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return CASE;
                        }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 314 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return WITH;
                        }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 319 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return AS;
                        }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 324 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return INT;
                        }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 329 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return FLOAT;
                        }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 334 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return STR;
                        }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 339 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return BOOL;
                        }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 344 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return LIST;
                        }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 349 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return PASS;
                        }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 355 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return ID;
                        }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 360 "scanner.l"
{
                            yylval.intval = atoi(yytext);
                            return INT_NUMBER;
                        }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 365 "scanner.l"
{
                            yylval.flval = atof(yytext);
                            return FLOAT_NUMBER;
                        }
	YY_BREAK

case 50:
YY_RULE_SETUP
#line 372 "scanner.l"
{
        BEGIN(INITIAL);
        return INDENT;
    }
	YY_BREAK


case 51:
YY_RULE_SETUP
#line 379 "scanner.l"
{

        int flag = 1;
        for (int i = 0; i <= top; i++) {
            if (current_indentation == stack_arr[i])
                flag = 0;
        }

        if(flag)
            return INDENTERROR;

        int end = 1;
        while(current_indentation < stack_arr[top])
        {
            unput(' ');
            BEGIN(DEDENTSTATE);
            end = 0;
            pop();

            return DEDENT;
        }

        if(end)
            BEGIN(INITIAL);

    }
	YY_BREAK


case 52:
YY_RULE_SETUP
#line 408 "scanner.l"
{
        if (top < 0)
            push(0);

        if (stack_arr[top] > 0) {
            while (top > 0) {
                unput(' ');
                BEGIN(DEDENTALLSTATE);
                pop();

                return DEDENT;
            }
        } else {
            BEGIN(INITIAL);
        }
    }
	YY_BREAK

case 53:
YY_RULE_SETUP
#line 426 "scanner.l"
{ string_buf_ptr = string_buf; BEGIN(DOUBLE_STRING); }    
	YY_BREAK

case 54:
YY_RULE_SETUP
#line 429 "scanner.l"
{*string_buf_ptr = '\0'; BEGIN(INITIAL); return STRING;} 
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 430 "scanner.l"
{              }
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 431 "scanner.l"
{printf("error in line %d\n", yylineno); BEGIN(INITIAL);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 432 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 433 "scanner.l"
{*string_buf_ptr++ = '\t';}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 434 "scanner.l"
{*string_buf_ptr++ = '\r';}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 435 "scanner.l"
{*string_buf_ptr++ = '\b';}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 436 "scanner.l"
{*string_buf_ptr++ = '\f';}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 437 "scanner.l"
{*string_buf_ptr++ = '\"';} 
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 438 "scanner.l"
{
        char *yptr = yytext;
        while ( *yptr )
            *string_buf_ptr++ = *yptr++;        
    }
	YY_BREAK

case 64:
YY_RULE_SETUP
#line 445 "scanner.l"
{ string_buf_ptr = string_buf; BEGIN(SINGLE_STRING); }    
	YY_BREAK

case 65:
YY_RULE_SETUP
#line 447 "scanner.l"
{*string_buf_ptr = '\0'; BEGIN(INITIAL); return STRING;}
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 448 "scanner.l"
{              }
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 449 "scanner.l"
{printf("line%d, ERROR: new line in string\n", yylineno); BEGIN(INITIAL);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 450 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 451 "scanner.l"
{*string_buf_ptr++ = '\t';}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 452 "scanner.l"
{*string_buf_ptr++ = '\r';}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 453 "scanner.l"
{*string_buf_ptr++ = '\b';}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 454 "scanner.l"
{*string_buf_ptr++ = '\f';}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 455 "scanner.l"
{*string_buf_ptr++ = '\'';} 
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 456 "scanner.l"
{
        char *yptr = yytext;
        while ( *yptr )
            *string_buf_ptr++ = *yptr++;        
    }
	YY_BREAK

case 75:
YY_RULE_SETUP
#line 463 "scanner.l"
{   
                            int i = 0;
                            strcpy(keyword, " ");

                            while(yytext[i] != ' ') {
                                if (yytext[i] == '\'') 
                                    break;

                                keyword[i] = yytext[i];
                                i++;
                            }

                            string_buf_ptr = string_buf; BEGIN(COMMENT_STRING); 

                            if (strcmp(keyword, "=") == 0) {
                                return yytext[0];
                            }
                            else if (strcmp(keyword, "(") == 0 || strcmp(keyword, "{") == 0 || strcmp(keyword, "[") == 0) {
                                return yytext[0];
                            }

                            else {
                                if ( strcmp(keyword, "return") == 0) {
                                    return RETURN;
                                }
                            }

                            
                        }
	YY_BREAK

case 76:
YY_RULE_SETUP
#line 494 "scanner.l"
{*string_buf_ptr = '\0'; BEGIN(INITIAL); return STRING;}
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 495 "scanner.l"
{}
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 496 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 497 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 498 "scanner.l"
{*string_buf_ptr++ = '\t';}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 499 "scanner.l"
{*string_buf_ptr++ = '\r';}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 500 "scanner.l"
{*string_buf_ptr++ = '\b';}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 501 "scanner.l"
{*string_buf_ptr++ = '\f';}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 502 "scanner.l"
{
        char *yptr = yytext;
        while ( *yptr )
            *string_buf_ptr++ = *yptr++;        
    }
	YY_BREAK

case 85:
YY_RULE_SETUP
#line 509 "scanner.l"
{   
                            int i = 0;
                            strcpy(keyword, " ");

                            while(yytext[i] != ' ') {
                                if (yytext[i] == '\"') 
                                    break;

                                keyword[i] = yytext[i];
                                i++;
                            }

                            string_buf_ptr = string_buf; BEGIN(COMMENT_STRING_DOUBLE); 

                            if (strcmp(keyword, "=") == 0) {
                                return yytext[0];
                            }

                            else if (strcmp(keyword, "(") == 0 || strcmp(keyword, "{") == 0 || strcmp(keyword, "[") == 0) {
                                return yytext[0];
                            }

                            else {
                                if ( strcmp(keyword, "return") == 0) {
                                    return RETURN;
                                }
                            }
                            
                        }
	YY_BREAK

case 86:
YY_RULE_SETUP
#line 540 "scanner.l"
{*string_buf_ptr = '\0'; BEGIN(INITIAL); return STRING;}
	YY_BREAK
case 87:
/* rule 87 can match eol */
YY_RULE_SETUP
#line 541 "scanner.l"
{}
	YY_BREAK
case 88:
/* rule 88 can match eol */
YY_RULE_SETUP
#line 542 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 543 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 544 "scanner.l"
{*string_buf_ptr++ = '\t';}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 545 "scanner.l"
{*string_buf_ptr++ = '\r';}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 546 "scanner.l"
{*string_buf_ptr++ = '\b';}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 547 "scanner.l"
{*string_buf_ptr++ = '\f';}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 548 "scanner.l"
{
        char *yptr = yytext;
        while ( *yptr )
            *string_buf_ptr++ = *yptr++;        
    }
	YY_BREAK

case 95:
YY_RULE_SETUP
#line 555 "scanner.l"
{printf("error in %d is %s",yylineno,yytext);}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 557 "scanner.l"
ECHO;
	YY_BREAK
#line 2062 "scanner.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,(yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,(yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 351 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 351 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 350);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc((yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 557 "scanner.l"

