#line 1 "scanner.cpp"

#line 3 "scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 3
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    #define yy_create_buffer yy_create_buffer

    #define yy_delete_buffer yy_delete_buffer

    #define yy_scan_buffer yy_scan_buffer

    #define yy_scan_string yy_scan_string

    #define yy_scan_bytes yy_scan_bytes

    #define yy_init_buffer yy_init_buffer

    #define yy_flush_buffer yy_flush_buffer

    #define yy_load_buffer_state yy_load_buffer_state

    #define yy_switch_to_buffer yy_switch_to_buffer

    #define yypush_buffer_state yypush_buffer_state

    #define yypop_buffer_state yypop_buffer_state

    #define yyensure_buffer_stack yyensure_buffer_stack

    #define yylex yylex

    #define yyrestart yyrestart

    #define yylex_init yylex_init

    #define yylex_init_extra yylex_init_extra

    #define yylex_destroy yylex_destroy

    #define yyget_debug yyget_debug

    #define yyset_debug yyset_debug

    #define yyget_extra yyget_extra

    #define yyset_extra yyset_extra

    #define yyget_in yyget_in

    #define yyset_in yyset_in

    #define yyget_out yyget_out

    #define yyset_out yyset_out

    #define yyget_leng yyget_leng

    #define yyget_text yyget_text

    #define yyget_lineno yyget_lineno

    #define yyset_lineno yyset_lineno

    #define yywrap yywrap

    #define yyalloc yyalloc

    #define yyrealloc yyrealloc

    #define yyfree yyfree

    #define yytext yytext

    #define yyleng yyleng

    #define yyin yyin

    #define yyout yyout

    #define yy_flex_debug yy_flex_debug

    #define yylineno yylineno

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 97
#define YY_END_OF_BUFFER 98
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[354] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   98,   96,
        5,    3,   54,    9,   65,   12,   12,   11,    7,   11,
        7,   48,    7,   23,   10,   24,   47,   47,   47,   47,
       12,   96,   11,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   64,   57,   55,   97,   75,   68,   66,   97,   85,
       79,   97,   97,   97,   95,   89,   97,   97,   50,   52,
       51,   53,    2,    0,    4,    0,    0,    9,    0,    0,
        0,   48,    0,    0,   25,    0,   27,   26,   47,   47,

       47,   47,    0,    0,    0,    0,    0,    6,   47,   40,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   14,   47,   30,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       64,   56,   63,   61,   62,   58,   60,   59,   75,   67,
       74,   72,   73,   69,   71,   70,   85,    0,   78,   83,
       84,   80,   82,   81,   95,    0,   88,   93,   94,   90,
       92,   91,    0,    4,    0,    0,    0,    0,    0,   49,
        1,   47,   47,   47,    0,    0,    0,    0,    0,    0,
        0,    0,    8,    0,   47,   47,   47,   47,   47,   47,

       13,   47,   47,   47,   47,   47,   29,   47,   47,    0,
       47,   47,   41,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   43,   35,   47,   47,   47,   77,   87,    0,
        0,    0,    0,    0,    0,   86,   76,   47,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   47,
       44,   47,   38,   47,   47,   15,   16,   47,   47,   47,
       47,   47,   47,   47,   45,   47,   47,   46,   47,   47,
       47,   47,   47,   39,   47,    0,    0,    0,    0,    0,
        0,    0,    8,    0,    8,   47,   17,   34,   47,   47,
       47,   42,   47,   47,   33,   47,   37,   47,   32,   31,

       47,   28,   21,    0,    0,    9,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   47,   36,
       47,   19,   47,   22,    4,    0,    0,    0,    0,    0,
        0,   47,   47,    0,    0,    0,    0,    0,    0,   18,
       20,    0,    8,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    1,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       17,   16,   16,   16,   16,   16,   16,   18,   19,   20,
       21,   22,    1,    1,   23,   23,   23,   23,   23,   24,
       23,   23,   23,   23,   23,   23,   23,   25,   23,   23,
       23,   23,   23,   26,   23,   23,   23,   23,   23,   23,
       27,   28,   29,    1,   30,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   23,   40,   41,   42,   43,
       44,   45,   23,   46,   47,   48,   49,   23,   50,   51,
       52,   23,   53,    1,   54,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[55] =
    {   0,
        1,    1,    2,    1,    3,    1,    4,    1,    1,    1,
        1,    5,    6,    1,    1,    7,    8,    1,    1,    1,
        1,    1,    7,    7,    7,    7,    1,    9,    5,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,   10,   10
    } ;

static const flex_int16_t yy_base[378] =
    {   0,
        0,    0,   52,   53,   56,   57,   62,   63,   69,   72,
     1067, 1066, 1065, 1064, 1063, 1062, 1061, 1060, 1063, 1072,
     1072,   97, 1057,    0, 1054,   66, 1072, 1072,   71,   45,
     1072,   78, 1057, 1038,  103, 1037,    0, 1026, 1012, 1009,
      104, 1051,    0,   36,   52,   75, 1018,   77,   88, 1011,
       94,  100, 1020, 1006, 1003,  102,  107, 1000, 1001,   49,
     1007,    0, 1072, 1072,  140,    0, 1072, 1072,  146,    0,
     1072, 1072, 1038,  155,    0, 1072, 1039,  161, 1072, 1072,
     1072, 1072,  110, 1038,    0, 1035, 1036,    0, 1033, 1034,
     1031,  130,  134,  111, 1072,  150, 1072, 1072,    0,  996,

      993,  965,  135,  128,  143,  194,  150, 1072,  971,  929,
      923,  922,  880,  890,  877,  125,  126,  884,  869,  867,
      864,  863,  858,  896,  852,  167,  887,  848,  838,  824,
      126,  771,  778,  138,  768,  769,  762,  774,  764,  776,
        0, 1072, 1072, 1072, 1072, 1072, 1072, 1072,    0, 1072,
     1072, 1072, 1072, 1072, 1072, 1072,    0,  803, 1072, 1072,
     1072, 1072, 1072, 1072,    0,  804, 1072, 1072, 1072, 1072,
     1072, 1072,  801,    0,  798,  799,  795,  796,  793,  151,
      198,  752,  762,  704,  185,  209,  213,  168,  210,  177,
      220,  203, 1072,  214,  703,  696,  705,  700,  687,  685,

      728,  695,  695,  692,  694,  692,  718,  678,  682,  223,
      667,  659,    0,  673,  656,  670,  661,  654,  650,  643,
      595,  582,    0,  626,  588,  590,  586, 1072, 1072,  621,
      618,  619,  618,  613,  606, 1072, 1072,  576,  217,  226,
      230,  229,  233,  237,  244,  263,  243,  245,  265,  564,
        0,  569,    0,  561,  562,  596,  586,  544,  538,  527,
      484,  466,  463,  475,    0,  470,  463,  502,  455,  466,
      462,  450,  459,  428,  394,  420,  419,  416,  413,  413,
      406,  294,  250,  348,  246,  364,  407,  403,  250,  244,
      250,    0,  249,  241,    0,  257,    0,  254,    0,    0,

      241,  279,  271,  259,  256, 1072,    0,  257,  398,  399,
      405,  434,    0,  401,  402,  482,  488,  517,  211,  252,
      198,  241,  168,  191, 1072,  485,  569,  568,    0,  570,
        0,  150,  129,  486,  576,  587,  575,  590,  605,   89,
       78,  634,  586,    0,  684,  687,  690,  712,  741,  693,
        0,  791, 1072,  820,  830,  840,  850,  860,  870,  874,
      880,  888,  898,  908,  918,  925,  935,  945,  951,  959,
      968,  977,  987,  997, 1006, 1015, 1025
    } ;

static const flex_int16_t yy_def[378] =
    {   0,
      353,    1,  354,  354,  355,  355,  356,  356,  357,  357,
      358,  358,  358,  358,  358,  358,  358,  358,  353,  353,
      353,  353,  353,  359,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  360,  360,  360,  360,
      361,  353,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  362,  353,  353,  353,  363,  353,  353,  353,  364,
      353,  353,  353,  353,  365,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  366,  353,  353,  359,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  360,  360,

      360,  360,  367,  368,  353,  353,  369,  353,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      362,  353,  353,  353,  353,  353,  353,  353,  363,  353,
      353,  353,  353,  353,  353,  353,  364,  353,  353,  353,
      353,  353,  353,  353,  365,  353,  353,  353,  353,  353,
      353,  353,  353,  366,  353,  370,  371,  353,  353,  353,
      353,  360,  360,  360,  367,  353,  372,  368,  353,  373,
      361,  353,  353,  369,  360,  360,  360,  360,  360,  360,

      360,  360,  360,  360,  360,  360,  360,  360,  360,  353,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  353,  353,  374,
      375,  370,  353,  371,  353,  353,  353,  360,  353,  367,
      367,  372,  368,  368,  373,  361,  367,  368,  353,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  374,  353,  375,  353,  353,
      353,  353,  367,  353,  368,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,

      360,  360,  360,  353,  353,  353,  282,  367,  376,  367,
      367,  353,  284,  376,  368,  368,  368,  353,  360,  360,
      360,  360,  360,  360,  353,  376,  377,  367,  312,  368,
      318,  360,  360,  376,  376,  376,  377,  367,  368,  360,
      360,  353,  376,  342,  376,  376,  376,  376,  353,  376,
      349,  376,    0,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353
    } ;

static const flex_int16_t yy_nxt[1127] =
    {   0,
       20,   21,   22,   21,   23,   24,   25,   26,   27,   28,
       28,   29,   30,   31,   28,   32,   32,   33,   31,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   27,   43,
       44,   45,   46,   47,   48,   49,   50,   37,   51,   37,
       52,   53,   54,   55,   56,   57,   58,   59,   37,   60,
       37,   61,   26,   27,   63,   63,   64,   64,   67,   67,
       92,   92,   68,   68,   71,   71,   72,   72,   73,   73,
       90,   76,   91,   77,   76,   90,   77,   91,  109,   65,
       65,  210,  110,   69,   69,   72,  138,  139,   72,   74,
       74,   93,  210,   92,   92,  111,   78,  112,   83,   78,

       83,   84,   85,   86,   96,  113,   96,   90,  103,   91,
      104,   83,  181,   83,  181,  114,  105,  117,  115,  106,
      106,   72,   72,   97,   72,   72,  119,  118,  120,  124,
      128,  121,  132,  122,  189,  125,  126,  134,  129,  186,
      127,  135,  142,   93,  143,   92,   92,  133,  150,  180,
      180,   96,  151,   96,   90,  190,   91,  159,  106,  106,
      201,  191,  187,  167,  202,  127,  180,  180,  217,  341,
      210,  144,  203,  127,  239,  145,  220,  152,  193,  188,
      221,  153,  146,  244,  340,  147,  160,  148,  154,  239,
      161,  155,  168,  156,  210,  190,  169,  162,  333,  181,

      163,  181,  164,  170,  245,  191,  171,  192,  172,  106,
      106,  212,  187,  236,  213,  185,  237,  241,  249,  249,
      191,  191,  193,  246,  247,  191,  248,   90,  191,   91,
      239,  185,  105,  241,  239,  106,  106,  193,  193,  239,
      242,  282,  193,  239,  210,  193,  188,  239,  284,  127,
      244,  239,  239,  187,  239,  210,  242,  187,  283,  332,
      190,  239,  325,  325,  190,  285,  246,  247,  282,  248,
      187,  245,  190,  190,  210,  105,  191,  187,  106,  106,
      249,  249,  210,  324,  187,  283,  323,  127,  127,  322,
      321,  320,  319,  193,  185,  185,  185,  307,  308,  185,

      309,  185,  185,  185,  185,  185,  310,  185,  185,  311,
      311,  185,  185,  185,  185,  185,  312,  312,  312,  312,
      185,  187,  185,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  185,  185,  188,  188,
      188,  313,  314,  188,  315,  188,  188,  188,  188,  188,
      316,  188,  188,  317,  317,  188,  188,  188,  188,  188,
      318,  318,  318,  318,  188,  190,  188,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,

      188,  188,  244,  239,  241,  244,  210,  241,  239,  239,
      210,  127,  306,  284,  311,  311,  282,  306,  328,  305,
      311,  311,  279,  304,  277,  327,  187,  303,  327,  190,
      285,  210,  187,  283,  185,  185,  185,  185,  239,  185,
      185,  185,  185,  185,  185,  282,  185,  185,  185,  329,
      329,  185,  185,  185,  185,  185,  329,  329,  329,  329,
      185,  187,  283,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  185,  185,  239,  244,
      244,  241,  241,  302,  239,  301,  300,  317,  317,  284,

      127,  330,  299,  317,  317,  210,  298,  297,  296,  190,
      295,  294,  327,  327,  293,  190,  285,  188,  188,  188,
      188,  188,  188,  239,  188,  188,  188,  188,  284,  188,
      188,  188,  331,  331,  188,  188,  188,  188,  188,  331,
      331,  331,  331,  188,  190,  285,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  188,
      188,  326,  239,  335,  292,  336,  239,  326,  291,  335,
      244,  336,  241,  338,  338,  339,  339,  342,  290,  210,
      244,  244,  241,  241,  239,  187,  337,  190,  342,  210,

      289,  282,  337,  327,  343,  338,  338,  288,  287,  286,
      127,  239,  281,  327,  327,  343,  284,  187,  283,  235,
      339,  339,  280,  233,  279,  277,  275,  274,  273,  210,
      272,  271,  190,  285,  326,  326,  326,  344,  345,  326,
      346,  326,  326,  326,  326,  326,  347,  326,  326,  348,
      348,  326,  326,  326,  326,  326,  349,  349,  349,  349,
      326,  327,  326,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  326,  326,  244,  270,
      241,  244,  269,  241,  244,  342,  241,  244,  342,  241,

      268,  267,  266,  265,  264,  348,  348,  263,  352,  352,
      262,  327,  343,  261,  327,  343,  244,  327,  241,  127,
      327,  210,  260,  342,  259,  350,  258,  348,  348,  257,
      256,  210,  255,  254,  253,  252,  251,  250,  127,  327,
      343,  326,  326,  326,  326,  244,  326,  241,  326,  326,
      326,  326,  342,  326,  326,  326,  351,  351,  326,  326,
      326,  326,  326,  351,  351,  351,  351,  326,  327,  343,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  326,  326,  244,  127,  241,  238,  237,

      236,  235,  342,  233,  231,  230,  352,  352,  229,  228,
      227,  226,  225,  224,  223,  222,  219,  218,  327,  343,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       88,  216,   88,   88,   88,   88,   88,   88,   88,   88,
       99,   99,  107,  107,  215,  107,  107,  107,  141,  214,
      210,  141,  141,  141,  141,  141,  211,  141,  149,  210,

      149,  209,  149,  149,  149,  149,  208,  149,  157,  207,
      206,  205,  157,  157,  157,  157,  204,  157,  165,  200,
      199,  165,  165,  165,  165,  174,  198,  174,  174,  174,
      174,  174,  174,  174,  174,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  194,  197,  194,  194,  232,
      232,  232,  232,  232,  232,  232,  196,  232,  234,  234,
      234,  234,  234,  234,  234,  195,  234,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  276,  276,  276,

      276,  276,  276,  276,  127,  276,  278,  278,  278,  278,
      278,  278,  278,  184,  278,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  183,  182,  179,  178,  177,
      176,  175,  173,  166,  158,  140,  137,  136,  127,  131,
      130,  123,  116,  108,  102,  101,  100,   98,   95,   94,
       89,   87,  353,   82,   82,   81,   81,   80,   80,   79,
       79,   19,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,

      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353
    } ;

static const flex_int16_t yy_chk[1127] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    3,    4,    5,    6,
       30,   30,    5,    6,    7,    8,    7,    8,    7,    8,
       26,    9,   26,    9,   10,   29,   10,   29,   44,    3,
        4,  341,   44,    5,    6,    9,   60,   60,   10,    7,
        8,   32,  340,   32,   32,   45,    9,   45,   22,   10,

       22,   22,   22,   22,   35,   46,   35,   35,   41,   35,
       41,   83,   94,   83,   94,   46,   41,   48,   46,   41,
       41,    9,    9,   35,   10,   10,   49,   48,   49,   51,
       52,   49,   56,   49,  104,   51,   51,   57,   52,  103,
       51,   57,   65,   92,   65,   92,   92,   56,   69,   93,
       93,   96,   69,   96,   96,  104,   96,   74,  105,  105,
      116,  107,  103,   78,  117,  116,  180,  180,  131,  333,
      126,   65,  117,  131,  188,   65,  134,   69,  107,  190,
      134,   69,   65,  190,  332,   65,   74,   65,   69,  185,
       74,   69,   78,   69,  324,  188,   78,   74,  323,  181,

       74,  181,   74,   78,  190,  106,   78,  106,   78,  106,
      106,  126,  185,  186,  126,  187,  189,  187,  192,  192,
      186,  189,  106,  191,  191,  194,  191,  210,  239,  210,
      240,  242,  191,  242,  241,  191,  191,  186,  189,  243,
      187,  241,  194,  244,  322,  239,  245,  247,  244,  321,
      245,  248,  285,  240,  283,  320,  242,  241,  241,  319,
      243,  308,  305,  304,  244,  244,  246,  246,  308,  246,
      247,  245,  248,  285,  303,  246,  249,  283,  246,  246,
      249,  249,  302,  301,  308,  308,  298,  296,  294,  293,
      291,  290,  289,  249,  282,  282,  282,  282,  282,  282,

      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,

      284,  284,  309,  310,  309,  314,  288,  314,  315,  311,
      287,  286,  281,  315,  310,  310,  311,  280,  311,  279,
      311,  311,  278,  277,  276,  309,  310,  275,  314,  315,
      315,  274,  311,  311,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  316,  326,
      334,  326,  334,  273,  317,  272,  271,  316,  316,  317,

      270,  317,  269,  317,  317,  268,  267,  266,  264,  316,
      263,  262,  326,  334,  261,  317,  317,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  327,  328,  327,  260,  327,  330,  337,  259,  337,
      335,  337,  335,  328,  328,  330,  330,  335,  258,  257,
      343,  336,  343,  336,  338,  328,  327,  330,  336,  256,

      255,  338,  337,  335,  335,  338,  338,  254,  252,  250,
      238,  339,  235,  343,  336,  336,  339,  338,  338,  234,
      339,  339,  233,  232,  231,  230,  227,  226,  225,  224,
      222,  221,  339,  339,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  345,  220,
      345,  346,  219,  346,  347,  345,  347,  350,  346,  350,

      218,  217,  216,  215,  214,  347,  347,  212,  350,  350,
      211,  345,  345,  209,  346,  346,  348,  347,  348,  208,
      350,  207,  206,  348,  205,  348,  204,  348,  348,  203,
      202,  201,  200,  199,  198,  197,  196,  195,  184,  348,
      348,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  352,  183,  352,  182,  179,

      178,  177,  352,  176,  175,  173,  352,  352,  166,  158,
      140,  139,  138,  137,  136,  135,  133,  132,  352,  352,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      359,  130,  359,  359,  359,  359,  359,  359,  359,  359,
      360,  360,  361,  361,  129,  361,  361,  361,  362,  128,
      127,  362,  362,  362,  362,  362,  125,  362,  363,  124,

      363,  123,  363,  363,  363,  363,  122,  363,  364,  121,
      120,  119,  364,  364,  364,  364,  118,  364,  365,  115,
      114,  365,  365,  365,  365,  366,  113,  366,  366,  366,
      366,  366,  366,  366,  366,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  369,  112,  369,  369,  370,
      370,  370,  370,  370,  370,  370,  111,  370,  371,  371,
      371,  371,  371,  371,  371,  110,  371,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  374,  374,  374,

      374,  374,  374,  374,  109,  374,  375,  375,  375,  375,
      375,  375,  375,  102,  375,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  101,  100,   91,   90,   89,
       87,   86,   84,   77,   73,   61,   59,   58,   55,   54,
       53,   50,   47,   42,   40,   39,   38,   36,   34,   33,
       25,   23,   19,   18,   17,   16,   15,   14,   13,   12,
       11,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,

      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[98] =
    {   0,
1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 2 "scanner.l"
    #include <stdio.h>
    #include <ctype.h>
    #include <stdlib.h>
    #include <string.h>
    #include "parser.tab.h"

    #pragma warning (disable: 4005)
    #include "parser.hpp"
    #include "astNodes.hpp"
    using namespace std;

    #define Stack_SIZE 100
    void push();
    void pop();
    void show();

    int top = -1;
    int stack_arr[Stack_SIZE];

    void push(int insert_item)
    {
        if (top == Stack_SIZE - 1)
            printf("\nOverflow!!");

        else
        {
            top++;
            stack_arr[top] = insert_item;
        }
    }

    void pop()
    {
        if (top == -1)
            printf("\nUnderflow!!");

        else
            top--;
    }

    void stackshow()
    {
        if (top == -1)
            printf("\nUnderflow!!");

        else
        {
            printf("\nElements present in the stack: \n");
            for (int i = top; i >= 0; --i)
                printf("%d\n", stack_arr[i]);
        }
    } 

    #define keyword_size 10
    char keyword[keyword_size];

    #define MAX_STR_CONST 256
    char string_buf[MAX_STR_CONST];
    char *string_buf_ptr;

    int current_indentation = 0;
    int spaces = 0;

    extern YYSTYPE yylval;
#line 978 "scanner.cpp"

#line 980 "scanner.cpp"

#define INITIAL 0
#define DOUBLE_STRING 1
#define SINGLE_STRING 2
#define COMMENT_STRING 3
#define COMMENT_STRING_DOUBLE 4
#define INDENTSTATE 5
#define DEDENTALLSTATE 6
#define DEDENTSTATE 7
#define NEWNEW 8

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 116 "scanner.l"


#line 1208 "scanner.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 354 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1072 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 118 "scanner.l"
{
                            BEGIN(INDENTSTATE);
                            if(top < 0)
                                push(0);

                            spaces = 0;
                            for(int i = 0; i < yyleng; i++){
                                if (yytext[i] == ' ') {
                                    spaces++;
                                } else if (yytext[i] == '\t') {
                                    spaces += 8;
                                }
                            }
                            push(spaces);

                            current_indentation = spaces;
                            unput(' ');

                            return NEWLINE;
                        }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 139 "scanner.l"
{
                            if(top < 0)
                                push(0);

                            spaces = 0;
                            for(int i = 0; i < yyleng; i++){
                                if (yytext[i] == ' ') {
                                    spaces++;
                                } else if (yytext[i] == '\t') {
                                    spaces += 8;
                                }
                            }
                            current_indentation = spaces;

                            unput(' ');
                            BEGIN(DEDENTSTATE);
                            return NEWLINE;
                        }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 158 "scanner.l"
{ 
                            BEGIN(DEDENTALLSTATE);
                            unput(' ');
                            return NEWLINE;
                        }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 164 "scanner.l"
{}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(DOUBLE_STRING):
case YY_STATE_EOF(SINGLE_STRING):
case YY_STATE_EOF(COMMENT_STRING):
case YY_STATE_EOF(COMMENT_STRING_DOUBLE):
case YY_STATE_EOF(INDENTSTATE):
case YY_STATE_EOF(DEDENTALLSTATE):
case YY_STATE_EOF(DEDENTSTATE):
case YY_STATE_EOF(NEWNEW):
#line 166 "scanner.l"
{
                    BEGIN(NEWNEW);
                    unput(' ');

                    if(stack_arr[top] == 0)
                        return 0;
                }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 175 "scanner.l"
{}
	YY_BREAK
case 6:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 177 "scanner.l"
{}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 179 "scanner.l"
{yylval.strval = strdup(yytext); return yytext[0];}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 181 "scanner.l"
{return ARRAY;}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 183 "scanner.l"
{}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 185 "scanner.l"
{yylval.strval = strdup(yytext); return yytext[0];}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 187 "scanner.l"
{yylval.strval = strdup(yytext); return yytext[0];}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 189 "scanner.l"
{yylval.strval = strdup(yytext); return yytext[0];} 
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 191 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return DEF;
                        }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 196 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return IF;
                        }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 201 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return ELIF;
                        }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 206 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return ELSE;
                        }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 211 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return BREAK;
                        }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 216 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return CONTINUE;
                        }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 221 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return GLOBAL;
                        }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 226 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return NONLOCAL;
                        }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 231 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return YIELD;
                        }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 236 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return RETURN;
                        }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 241 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return LT;
                        }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 246 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return GT;
                        }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 251 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return LTE;
                        }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 256 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return GTE;
                        }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 261 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return EQUAL;
                        }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 266 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return WHILE;
                        }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 271 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return FOR;
                        }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 276 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return IN;
                        }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 281 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return RANGE;
                        }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 286 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return PRINT;
                        }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 291 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return INPUT;
                        }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 296 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return CLASS;
                        }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 301 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return TRY;
                        }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 306 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return EXCEPT;
                        }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 311 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return MATCH;
                        }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 316 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return CASE;
                        }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 321 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return WITH;
                        }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 326 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return AS;
                        }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 331 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return INT;
                        }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 336 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return FLOAT;
                        }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 341 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return STR;
                        }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 346 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return BOOL;
                        }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 351 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return LIST;
                        }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 356 "scanner.l"
{
                            yylval.strval = strdup(yytext);
                            return PASS;
                        }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 362 "scanner.l"
{
                            yylval.astNode = new IdentifierNode("IDENTIFIER", "Identifier", yytext);
                            return ID;
                        }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 367 "scanner.l"
{
                            yylval.astNode = new NumberNode("INT", "int", atoi(yytext));
                            return INT_NUMBER;
                        }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 372 "scanner.l"
{
                            yylval.astNode = new NumberNode("FLOAT", "float", atoi(yytext));
                            return FLOAT_NUMBER;
                        }
	YY_BREAK

case 50:
YY_RULE_SETUP
#line 379 "scanner.l"
{
        BEGIN(INITIAL);
        return INDENT;
    }
	YY_BREAK


case 51:
YY_RULE_SETUP
#line 386 "scanner.l"
{

        int flag = 1;
        for (int i = 0; i <= top; i++) {
            if (current_indentation == stack_arr[i])
                flag = 0;
        }

        if(flag)
            return INDENTERROR;

        int end = 1;
        while(current_indentation < stack_arr[top])
        {
            unput(' ');
            BEGIN(DEDENTSTATE);
            end = 0;
            pop();

            return DEDENT;
        }

        if(end)
            BEGIN(INITIAL);

    }
	YY_BREAK


case 52:
YY_RULE_SETUP
#line 415 "scanner.l"
{
        if (top < 0)
            push(0);

        if (stack_arr[top] > 0) {
            while (top > 0) {
                unput(' ');
                BEGIN(DEDENTALLSTATE);
                pop();

                return DEDENT;
            }
        } else {
            BEGIN(INITIAL);
        }
    }
	YY_BREAK


case 53:
YY_RULE_SETUP
#line 434 "scanner.l"
{
        BEGIN(DEDENTALLSTATE);
        unput(' ');
        return NEWLINE;
    }
	YY_BREAK

case 54:
YY_RULE_SETUP
#line 442 "scanner.l"
{ string_buf_ptr = string_buf; BEGIN(DOUBLE_STRING); }    
	YY_BREAK

case 55:
YY_RULE_SETUP
#line 445 "scanner.l"
{*string_buf_ptr = '\0'; BEGIN(INITIAL); yylval.astNode = new StringNode("STRING", "string", string_buf); return STRING;} 
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 446 "scanner.l"
{              }
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 447 "scanner.l"
{printf("error in line %d\n", yylineno); BEGIN(INITIAL);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 448 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 449 "scanner.l"
{*string_buf_ptr++ = '\t';}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 450 "scanner.l"
{*string_buf_ptr++ = '\r';}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 451 "scanner.l"
{*string_buf_ptr++ = '\b';}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 452 "scanner.l"
{*string_buf_ptr++ = '\f';}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 453 "scanner.l"
{*string_buf_ptr++ = '\"';} 
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 454 "scanner.l"
{
        char *yptr = yytext;
        while ( *yptr )
            *string_buf_ptr++ = *yptr++;        
    }
	YY_BREAK

case 65:
YY_RULE_SETUP
#line 461 "scanner.l"
{ string_buf_ptr = string_buf; BEGIN(SINGLE_STRING); }    
	YY_BREAK

case 66:
YY_RULE_SETUP
#line 463 "scanner.l"
{*string_buf_ptr = '\0'; BEGIN(INITIAL); yylval.astNode = new StringNode("STRING", "string", string_buf); return STRING;}
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 464 "scanner.l"
{              }
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 465 "scanner.l"
{printf("line%d, ERROR: new line in string\n", yylineno); BEGIN(INITIAL);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 466 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 467 "scanner.l"
{*string_buf_ptr++ = '\t';}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 468 "scanner.l"
{*string_buf_ptr++ = '\r';}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 469 "scanner.l"
{*string_buf_ptr++ = '\b';}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 470 "scanner.l"
{*string_buf_ptr++ = '\f';}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 471 "scanner.l"
{*string_buf_ptr++ = '\'';} 
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 472 "scanner.l"
{
        char *yptr = yytext;
        while ( *yptr )
            *string_buf_ptr++ = *yptr++;        
    }
	YY_BREAK

case 76:
YY_RULE_SETUP
#line 479 "scanner.l"
{   
                            int i = 0;
                            strcpy(keyword, " ");

                            while(yytext[i] != ' ') {
                                if (yytext[i] == '\'') 
                                    break;

                                keyword[i] = yytext[i];
                                i++;
                            }

                            string_buf_ptr = string_buf; BEGIN(COMMENT_STRING); 

                            if (strcmp(keyword, "=") == 0) {
                                return yytext[0];
                            }
                            else if (strcmp(keyword, "(") == 0 || strcmp(keyword, "{") == 0 || strcmp(keyword, "[") == 0) {
                                return yytext[0];
                            }

                            else {
                                if ( strcmp(keyword, "return") == 0) {
                                    return RETURN;
                                }
                            }

                            
                        }
	YY_BREAK

case 77:
YY_RULE_SETUP
#line 510 "scanner.l"
{*string_buf_ptr = '\0'; BEGIN(INITIAL); yylval.astNode = new StringNode("STRING", "string", string_buf); return STRING;}
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 511 "scanner.l"
{}
	YY_BREAK
case 79:
/* rule 79 can match eol */
YY_RULE_SETUP
#line 512 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 513 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 514 "scanner.l"
{*string_buf_ptr++ = '\t';}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 515 "scanner.l"
{*string_buf_ptr++ = '\r';}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 516 "scanner.l"
{*string_buf_ptr++ = '\b';}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 517 "scanner.l"
{*string_buf_ptr++ = '\f';}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 518 "scanner.l"
{
        char *yptr = yytext;
        while ( *yptr )
            *string_buf_ptr++ = *yptr++;        
    }
	YY_BREAK

case 86:
YY_RULE_SETUP
#line 525 "scanner.l"
{   
                            int i = 0;
                            strcpy(keyword, " ");

                            while(yytext[i] != ' ') {
                                if (yytext[i] == '\"') 
                                    break;

                                keyword[i] = yytext[i];
                                i++;
                            }

                            string_buf_ptr = string_buf; BEGIN(COMMENT_STRING_DOUBLE); 

                            if (strcmp(keyword, "=") == 0) {
                                return yytext[0];
                            }

                            else if (strcmp(keyword, "(") == 0 || strcmp(keyword, "{") == 0 || strcmp(keyword, "[") == 0) {
                                return yytext[0];
                            }

                            else {
                                if ( strcmp(keyword, "return") == 0) {
                                    return RETURN;
                                }
                            }
                            
                        }
	YY_BREAK

case 87:
YY_RULE_SETUP
#line 556 "scanner.l"
{*string_buf_ptr = '\0'; BEGIN(INITIAL); yylval.astNode = new StringNode("STRING", "string", string_buf); return STRING;}
	YY_BREAK
case 88:
/* rule 88 can match eol */
YY_RULE_SETUP
#line 557 "scanner.l"
{}
	YY_BREAK
case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 558 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 559 "scanner.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 560 "scanner.l"
{*string_buf_ptr++ = '\t';}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 561 "scanner.l"
{*string_buf_ptr++ = '\r';}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 562 "scanner.l"
{*string_buf_ptr++ = '\b';}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 563 "scanner.l"
{*string_buf_ptr++ = '\f';}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 564 "scanner.l"
{
        char *yptr = yytext;
        while ( *yptr )
            *string_buf_ptr++ = *yptr++;        
    }
	YY_BREAK

case 96:
YY_RULE_SETUP
#line 571 "scanner.l"
{printf("error in %d is %s",yylineno,yytext);}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 573 "scanner.l"
ECHO;
	YY_BREAK
#line 2081 "scanner.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,(yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,(yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 354 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 354 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 353);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc((yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 573 "scanner.l"

